unit DMImportarStock;

interface

uses
  System.SysUtils, System.Classes, Data.FMTBcd, FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.Stan.Param,
  FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf, FireDAC.DApt.Intf, FireDAC.Stan.Async, FireDAC.DApt,
  FireDAC.Comp.DataSet, FireDAC.Comp.Client, Datasnap.DBClient, Datasnap.Provider, Data.DB, Data.SqlExpr, IBGenerator,
  FireDAC.UI.Intf, FireDAC.Stan.Def, FireDAC.Stan.Pool, FireDAC.Phys, FireDAC.VCLUI.Wait, FireDAC.Comp.UI,
  FireDAC.Phys.IB, FireDAC.Phys.IBBase, FireDAC.Phys.FB, FireDAC.Phys.FBDef,
  FireDAC.Phys.IBDef;

type
  TDatosImportarStock = class(TDataModule)
    DSPDep: TDataSetProvider;
    CDSDep: TClientDataSet;
    CDSDepID_DEPOSITO: TIntegerField;
    CDSDepCODIGO_DEPOSITO: TIntegerField;
    CDSDepCODIGO_STK: TStringField;
    CDSDepSUCURSAL: TIntegerField;
    CDSDepAVISO_MINIMOSTOCK: TStringField;
    QDep: TFDQuery;
    QDepID_DEPOSITO: TIntegerField;
    QDepCODIGO_DEPOSITO: TIntegerField;
    QDepCODIGO_STK: TStringField;
    QDepSUCURSAL: TIntegerField;
    QDepINICIAL: TFloatField;
    QDepMINIMO: TFloatField;
    QDepMEDIO: TFloatField;
    QDepFISICO: TFloatField;
    QDepRECARGO: TFloatField;
    QDepFUAPRECIOS: TSQLTimeStampField;
    QDepSECTOR: TStringField;
    QDepUBICACION: TStringField;
    QDepFULTAJUSTE: TSQLTimeStampField;
    QDepUNIDADES: TFloatField;
    QDepAVISO_MINIMOSTOCK: TStringField;
    CDSDepINICIAL: TFloatField;
    CDSDepMINIMO: TFloatField;
    CDSDepMEDIO: TFloatField;
    CDSDepFISICO: TFloatField;
    CDSDepRECARGO: TFloatField;
    CDSDepFUAPRECIOS: TSQLTimeStampField;
    CDSDepSECTOR: TStringField;
    CDSDepUBICACION: TStringField;
    CDSDepFULTAJUSTE: TSQLTimeStampField;
    CDSDepUNIDADES: TFloatField;
    ibgIdDep: TIBGenerator;
    DSPMarca: TDataSetProvider;
    CDSMarca: TClientDataSet;
    CDSMarcaMARCA_STK: TStringField;
    CDSMarcaDESCRIPCION_MARCA: TStringField;
    CDSMarcaOBSERVACION_MARCA: TStringField;
    QMarca: TFDQuery;
    QMarcaMARCA_STK: TStringField;
    QMarcaDESCRIPCION_MARCA: TStringField;
    QMarcaOBSERVACION_MARCA: TStringField;
    DSPRubro: TDataSetProvider;
    CDSRubro: TClientDataSet;
    CDSRubroCODIGO_RUBRO: TStringField;
    CDSRubroDETALLE_RUBRO: TStringField;
    CDSRubroCONTROL_RUBRO: TStringField;
    CDSRubroFUERA_PROMO: TStringField;
    CDSRubroORDEN: TIntegerField;
    QRubro: TFDQuery;
    QRubroCODIGO_RUBRO: TStringField;
    QRubroDETALLE_RUBRO: TStringField;
    QRubroCONTROL_RUBRO: TStringField;
    QRubroFUERA_PROMO: TStringField;
    QRubroORDEN: TIntegerField;
    FDConnection: TFDConnection;
    QBorrarArticulo: TFDQuery;
    QInactivarStk: TFDQuery;
    QVerificaStockConMov: TFDQuery;
    QVerificaStockConMovESTADO: TStringField;
    FDPhysFBDriverLink1: TFDPhysFBDriverLink;
    FDPhysIBDriverLink1: TFDPhysIBDriverLink;
    FDGUIxWaitCursor1: TFDGUIxWaitCursor;
    QStockLocal: TFDQuery;
    QStockLocalCODIGO_STK: TStringField;
    DSPSubRubro: TDataSetProvider;
    CDSSubRubro: TClientDataSet;
    CDSSubRubroCODIGO_SUBRUBRO: TStringField;
    CDSSubRubroDETALLE_SUBRUBRO: TStringField;
    CDSSubRubroCODIGO_RUBRO: TStringField;
    CDSSubRubroCONTROL_SUBRUBRO: TStringField;
    CDSSubRubroFUERA_PROMO: TStringField;
    QSubRubro: TFDQuery;
    QSubRubroCODIGO_SUBRUBRO: TStringField;
    QSubRubroDETALLE_SUBRUBRO: TStringField;
    QSubRubroCODIGO_RUBRO: TStringField;
    QSubRubroCONTROL_SUBRUBRO: TStringField;
    QSubRubroFUERA_PROMO: TStringField;
    QCodigoBarra: TFDQuery;
    QCodigoBarraID: TIntegerField;
    QCodigoBarraCODIGO_STK: TStringField;
    QCodigoBarraCODIGOBARRA: TStringField;
    QCodigoBarraPRESENTACION: TIntegerField;
    QCodigoBarraPRESENTACION_CANTIDAD: TFloatField;
    CDSCodigoBarra: TClientDataSet;
    CDSCodigoBarraID: TIntegerField;
    CDSCodigoBarraCODIGO_STK: TStringField;
    CDSCodigoBarraCODIGOBARRA: TStringField;
    CDSCodigoBarraPRESENTACION: TIntegerField;
    CDSCodigoBarraPRESENTACION_CANTIDAD: TFloatField;
    DSPCodigoBarra: TDataSetProvider;
    ibgCodBarra: TIBGenerator;
    DSPDepositos: TDataSetProvider;
    CDSDepositos: TClientDataSet;
    CDSDepositosID: TIntegerField;
    CDSDepositosNOMBRE: TStringField;
    CDSDepositosSUCURSAL: TIntegerField;
    CDSDepositosCENTRALIZA_STOCK: TStringField;
    QDepositos: TFDQuery;
    QDepositosID: TIntegerField;
    QDepositosNOMBRE: TStringField;
    QDepositosSUCURSAL: TIntegerField;
    QDepositosCENTRALIZA_STOCK: TStringField;
    QListaPrecios: TFDQuery;
    QListaPreciosID: TIntegerField;
    QListaPreciosID_CAB: TIntegerField;
    QListaPreciosRUBRO: TStringField;
    QListaPreciosSUBRUBRO: TStringField;
    QListaPreciosCODIGOARTICULO: TStringField;
    QListaPreciosCOSTO_GRAVADO: TFloatField;
    QListaPreciosCOSTO_EXENTO: TFloatField;
    QListaPreciosCOSTO_TOTAL: TFloatField;
    QListaPreciosIVA_TASA: TFloatField;
    QListaPreciosRECARGO: TFloatField;
    QListaPreciosPRECIO_GRAVADO: TFloatField;
    QListaPreciosIVA_IMPORTE: TFloatField;
    QListaPreciosPRECIO_EXENTO: TFloatField;
    QListaPreciosPRECIO: TFloatField;
    QListaPreciosDESCUENTO: TFloatField;
    QListaPreciosREC_APLICAR: TFloatField;
    QListaPreciosFECHA: TSQLTimeStampField;
    DSPListaPrecios: TDataSetProvider;
    CDSListaPrecios: TClientDataSet;
    CDSListaPreciosID: TIntegerField;
    CDSListaPreciosID_CAB: TIntegerField;
    CDSListaPreciosRUBRO: TStringField;
    CDSListaPreciosSUBRUBRO: TStringField;
    CDSListaPreciosCODIGOARTICULO: TStringField;
    CDSListaPreciosCOSTO_GRAVADO: TFloatField;
    CDSListaPreciosCOSTO_EXENTO: TFloatField;
    CDSListaPreciosCOSTO_TOTAL: TFloatField;
    CDSListaPreciosIVA_TASA: TFloatField;
    CDSListaPreciosRECARGO: TFloatField;
    CDSListaPreciosPRECIO_GRAVADO: TFloatField;
    CDSListaPreciosIVA_IMPORTE: TFloatField;
    CDSListaPreciosPRECIO_EXENTO: TFloatField;
    CDSListaPreciosPRECIO: TFloatField;
    CDSListaPreciosDESCUENTO: TFloatField;
    CDSListaPreciosREC_APLICAR: TFloatField;
    CDSListaPreciosFECHA: TSQLTimeStampField;
    ibgListaPrecio: TIBGenerator;
    QStock: TFDQuery;
    QStockCODIGO_STK: TStringField;
    QStockDETALLE_STK: TStringField;
    QStockDETALLE_STK_ADICIONAL: TStringField;
    QStockCODIGO_BARRAS: TStringField;
    QStockRUBRO_STK: TStringField;
    QStockSUBRUBRO_STK: TStringField;
    QStockMARCA_STK: TStringField;
    QStockTASA_IVA: TIntegerField;
    QStockSOBRETASA_IVA: TIntegerField;
    QStockCOSTO_GRAVADO_STK: TFloatField;
    QStockCOSTO_IVA: TFloatField;
    QStockCOSTO_FINAL: TFloatField;
    QStockCOSTO_EXENTO_STK: TFloatField;
    QStockCOSTO_TOTAL_STK: TFloatField;
    QStockREEMPLAZO_STK: TStringField;
    QStockFIJACION_PRECIO_GRAVADO: TFloatField;
    QStockFIJACION_PRECIO_IVA: TFloatField;
    QStockFIJACION_PRECIO_FINAL: TFloatField;
    QStockFIJACION_PRECIO_EXENTO: TFloatField;
    QStockFIJACION_PRECIO_TOTAL: TFloatField;
    QStockFUAP: TDateField;
    QStockUNIDAD: TStringField;
    QStockCONTROLASTOCK: TStringField;
    QStockCODIGO_PROVEEDOR: TStringField;
    QStockCLASE_ARTICULO: TIntegerField;
    QStockMODO_GRAVAMEN: TStringField;
    QStockCON_IMP_INT: TStringField;
    QStockIMPUESTO_INTERNOS: TFloatField;
    QStockGRAVADO_IB: TStringField;
    QStockTASA_IB: TIntegerField;
    QStockACTUALIZACOSTO: TStringField;
    QStockDEPRODUCCION: TStringField;
    QStockPRODUCCIONDIRECTA: TStringField;
    QStockUNIDAD_COMPRA: TStringField;
    QStockCONTENIDO_COMPRA: TFloatField;
    QStockCONTROL_SERIE: TStringField;
    QStockUSA_CODIGOBARRA: TStringField;
    QStockUNIDAD_ULTIMAUSADA: TStringField;
    QStockID_TABLAPRECIOS: TIntegerField;
    QStockID_TABLAPRECIOSDETALLE: TIntegerField;
    QStockCODIGO_PRECIO: TIntegerField;
    QStockFECHA_ALTA: TDateField;
    QStockCOSTO_GRAVADO_SOMBRA: TFloatField;
    QStockCOSTO_EXENTO_SOMBRA: TFloatField;
    QStockFECHA_ACT_SOMBRA: TDateField;
    QStockFECHA_ULTIMAVTA: TDateField;
    QStockMONEDA: TIntegerField;
    QStockCOSTO_GRAVADO_P: TFloatField;
    QStockCOSTO_EXENTO_P: TFloatField;
    QStockCOSTO_TOTAL_P: TFloatField;
    QStockPOSICION: TStringField;
    QStockPRESENTACION_UNIDAD: TStringField;
    QStockPRESENTACION_CANTIDAD: TFloatField;
    QStockEDITAPRECIO: TStringField;
    QStockEDITADETALLE: TStringField;
    QStockURL: TStringField;
    QStockFECHA_ULTIMA_COMPRA: TDateField;
    QStockCOMANDA: TStringField;
    QStockPORCENTAJE_SOBRECOSTO: TFloatField;
    QStockRUBRO_GASTO: TStringField;
    QStockRUBRO_CTA_GASTO: TStringField;
    QStockPUBLICAR_WEB: TStringField;
    QStockGTIA_MESES: TIntegerField;
    QStockGARANTIAOFICIAL: TStringField;
    QStockADICIONAL_SOBRECOSTO: TFloatField;
    QStockIMPRIMIR_LSTPRECIOS: TStringField;
    QStockCONTROL_TRAZABILIDAD: TStringField;
    QStockIVA_MODIFICADO: TStringField;
    QStockSIGLAS: TStringField;
    QStockPRESENTACION_2_CANT: TFloatField;
    QStockTASA_MANUFACTURA: TStringField;
    QStockPLU: TStringField;
    QStockACOPIABLE: TStringField;
    QStockCIKO_TIPO: TIntegerField;
    QStockLARGO_1: TFloatField;
    QStockLARGO_2: TFloatField;
    QStockLARGO_3: TFloatField;
    QStockMODO_IVA: TStringField;
    QStockROTURA_1: TFloatField;
    QStockROTURA_2: TFloatField;
    QStockCIMA: TFloatField;
    QStockBASE: TFloatField;
    QStockVOLUMEN: TFloatField;
    QStockPESO: TFloatField;
    QStockDIAMETRO_OLLA: TFloatField;
    QStockALTO_ACC: TFloatField;
    QStockTIPOADICIONAL: TStringField;
    QStockPESO_CALCULADO: TFloatField;
    QStockDISPONIBLE: TStringField;
    QDescuentos: TFDQuery;
    DSPDescuentos: TDataSetProvider;
    CDSDescuentos: TClientDataSet;
    QDescuentosCODIGO: TStringField;
    QDescuentosDESCUENTO: TFloatField;
    QDescuentosPRECIO: TFloatField;
    QDescuentosDESDE: TSQLTimeStampField;
    QDescuentosHASTA: TSQLTimeStampField;
    QDescuentosSOLOCLIENTES: TStringField;
    QDescuentosAPLICA_LUNES: TStringField;
    QDescuentosAPLICA_MARTES: TStringField;
    QDescuentosAPLICA_MIERCOLES: TStringField;
    QDescuentosAPLICA_JUEVES: TStringField;
    QDescuentosAPLICA_VIERNES: TStringField;
    QDescuentosAPLICA_SABADOS: TStringField;
    QDescuentosAPLICA_DOMINGO: TStringField;
    QDescuentosAPLICA_ALL_DAYS: TStringField;
    CDSDescuentosCODIGO: TStringField;
    CDSDescuentosDESCUENTO: TFloatField;
    CDSDescuentosPRECIO: TFloatField;
    CDSDescuentosDESDE: TSQLTimeStampField;
    CDSDescuentosHASTA: TSQLTimeStampField;
    CDSDescuentosSOLOCLIENTES: TStringField;
    CDSDescuentosAPLICA_LUNES: TStringField;
    CDSDescuentosAPLICA_MARTES: TStringField;
    CDSDescuentosAPLICA_MIERCOLES: TStringField;
    CDSDescuentosAPLICA_JUEVES: TStringField;
    CDSDescuentosAPLICA_VIERNES: TStringField;
    CDSDescuentosAPLICA_SABADOS: TStringField;
    CDSDescuentosAPLICA_DOMINGO: TStringField;
    CDSDescuentosAPLICA_ALL_DAYS: TStringField;
    QBorrarDsctos: TFDQuery;
    StringField1: TStringField;
    FloatField1: TFloatField;
    FloatField2: TFloatField;
    SQLTimeStampField1: TSQLTimeStampField;
    SQLTimeStampField2: TSQLTimeStampField;
    StringField2: TStringField;
    StringField3: TStringField;
    StringField4: TStringField;
    StringField5: TStringField;
    StringField6: TStringField;
    StringField7: TStringField;
    StringField8: TStringField;
    StringField9: TStringField;
    StringField10: TStringField;
    QStockPRESENTACION_TOLERANCIA: TFloatField;
    QStockPERCIBE_IVA: TStringField;
    QStockID_TASA_PERCEP_IVA: TIntegerField;
    QStockAPLICA_TASA_DIF: TStringField;
    QStockPLU_SECCION: TStringField;
    QStockDESCRIPCION_CORTA: TMemoField;
    QStockDESCRIPCION_LARGA: TMemoField;
    QStockCATEGORIAS_WEB: TStringField;
    QDepositosCENTRALIZA_WEB: TStringField;
    CDSDepositosCENTRALIZA_WEB: TStringField;
    QStockDETALLE_CORTO: TStringField;
    QStockPLU_2: TStringField;
    QStockARTICULO_VARIABLE: TStringField;
    QStockFOB: TSingleField;
    QStockCODIGO_ART_VARIABLE: TStringField;
    QStockDIAS_VENCIMIENTO: TIntegerField;
    QStockFOTO: TBlobField;
    QStockDETALLE_NORM: TStringField;
    QDepositosACTIVO: TStringField;
    CDSDepositosACTIVO: TStringField;
    QStockSECTOR_PRODUCCION: TIntegerField;
    procedure DataModuleDestroy(Sender: TObject);
    procedure CDSDepNewRecord(DataSet: TDataSet);
    procedure CDSListaPreciosNewRecord(DataSet: TDataSet);
    procedure CDSCodigoBarraNewRecord(DataSet: TDataSet);
    procedure QStockNewRecord(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DatosImportarStock: TDatosImportarStock;

implementation

{%CLASSGROUP 'Vcl.Controls.TControl'}

uses UDMain_FD;
{$R *.dfm}

procedure TDatosImportarStock.CDSCodigoBarraNewRecord(DataSet: TDataSet);
begin
  CDSCodigoBarraID.Value:=ibgCodBarra.IncrementFD(1);
end;

procedure TDatosImportarStock.CDSDepNewRecord(DataSet: TDataSet);
begin
  CDSDep.FieldByName('id_deposito').Value := ibgIdDep.IncrementFD(1);
  CDSDep.FieldByName('Inicial').AsFloat   := 0;
  CDSDep.FieldByName('Minimo').AsFLoat    := 0;
  CDSDep.FieldByName('Medio').AsFloat     := 0;
  CDSDep.FieldByName('Fisico').AsFloat    := 0;
  CDSDep.FieldByName('Recargo').AsFLoat   := 0;
  CDSDep.FieldByName('Unidades').AsFloat  := 1;
end;

procedure TDatosImportarStock.CDSListaPreciosNewRecord(DataSet: TDataSet);
begin
  CDSListaPreciosID.Value     := ibgListaPrecio.IncrementFD(1);
end;

procedure TDatosImportarStock.DataModuleDestroy(Sender: TObject);
begin
  DatosImportarStock:=NIL;
end;

procedure TDatosImportarStock.QStockNewRecord(DataSet: TDataSet);
begin
  QStockIVA_MODIFICADO.Value        := 'N';
  QStockPRESENTACION_2_CANT.AsFloat := 1;
  QStockTASA_MANUFACTURA.Value      := 'N';
  QStockPLU.Value                   := '';
  QStockACOPIABLE.Value             := 'S';
  QStockMODO_IVA.Value              := 'A';
  QStockCIKO_TIPO.Value             := 0;
  QStockLARGO_1.Value               := 0;
  QStockLARGO_2.Value               := 0;
  QStockLARGO_3.Value               := 0;
  QStockROTURA_1.Value              := 0;
  QStockROTURA_2.Value              := 0;
  QStockCIMA.Value                  := 0;
  QStockBASE.Value                  := 0;
  QStockVOLUMEN.Value               := 0;
  QStockPESO.Value                  := 0;
  QStockDIAMETRO_OLLA.Value         := 0;
  QStockALTO_ACC.Value              := 0;
  QStockCIMA.Value                  := 0;
  QStockPESO_CALCULADO.Value        := 0;
  QStockDISPONIBLE.Value            :='S';
end;

end.
