unit DMImportacion;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr, WideStrings,
  IBGenerator, Data.DBXInterBase, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Error, FireDAC.UI.Intf, FireDAC.Phys.Intf, FireDAC.Stan.Def,
  FireDAC.Stan.Pool, FireDAC.Stan.Async, FireDAC.Phys, FireDAC.Stan.Param,
  FireDAC.DatS, FireDAC.DApt.Intf, FireDAC.DApt, FireDAC.Comp.DataSet,
  FireDAC.Comp.Client, FireDAC.VCLUI.Wait, FireDAC.Phys.IB, FireDAC.Phys.IBBase,
  FireDAC.Phys.FB, FireDAC.Comp.UI, FireDAC.Phys.FBDef, FireDAC.Phys.IBDef,
  RemoteDB.Client.Dataset, RemoteDB.Client.Database;

type
  TDatosImportacion = class(TDataModule)
    DSFcVTaCab: TDataSource;
    DSFcVtaDet: TDataSource;
    DSFcVtaImp: TDataSource;
    DSCajaMov: TDataSource;
    DSComprobantes: TDataSource;
    DSBuscaSucursal: TDataSource;
    DSDebitos: TDataSource;
    DSTransBco: TDataSource;
    DSChe3: TDataSource;
    DSMovTCredito: TDataSource;
    DSMovEfectivo: TDataSource;
    DSAjusteDet: TDataSource;
    DSAjusteCab: TDataSource;
    DSAjusteSubDetalle: TDataSource;
    FDConnection: TFDConnection;
    QFcVtaCab: TFDQuery;
    QFcVtaCabID_FC: TIntegerField;
    QFcVtaCabTIPOCPBTE: TStringField;
    QFcVtaCabCLASECPBTE: TStringField;
    QFcVtaCabCODIGO: TStringField;
    QFcVtaCabNROCPBTE: TStringField;
    QFcVtaCabLETRAFAC: TStringField;
    QFcVtaCabSUCFAC: TStringField;
    QFcVtaCabNUMEROFAC: TStringField;
    QFcVtaCabNOMBRE: TStringField;
    QFcVtaCabRAZONSOCIAL: TStringField;
    QFcVtaCabDIRECCION: TStringField;
    QFcVtaCabCPOSTAL: TStringField;
    QFcVtaCabLOCALIDAD: TStringField;
    QFcVtaCabTIPOIVA: TIntegerField;
    QFcVtaCabCUIT: TStringField;
    QFcVtaCabLISTAPRECIO: TIntegerField;
    QFcVtaCabCONDICIONVTA: TIntegerField;
    QFcVtaCabANULADO: TStringField;
    QFcVtaCabNRORTO: TStringField;
    QFcVtaCabN_OPERACION2: TFloatField;
    QFcVtaCabNETOGRAV1: TFloatField;
    QFcVtaCabNETOGRAV2: TFloatField;
    QFcVtaCabNETONOGRAV1: TFloatField;
    QFcVtaCabNETONOGRAV2: TFloatField;
    QFcVtaCabDSTO: TFloatField;
    QFcVtaCabDSTOIMPORTE: TFloatField;
    QFcVtaCabNETOEXEN1: TFloatField;
    QFcVtaCabNETOEXEN2: TFloatField;
    QFcVtaCabTOTAL: TFloatField;
    QFcVtaCabDEBE: TFloatField;
    QFcVtaCabIMPRESO: TStringField;
    QFcVtaCabOBSERVACION1: TStringField;
    QFcVtaCabOBSERVACION2: TStringField;
    QFcVtaCabCPTE_MANUAL: TStringField;
    QFcVtaCabSUCURSAL: TIntegerField;
    QFcVtaCabFACTURANRO: TStringField;
    QFcVtaCabZONA: TIntegerField;
    QFcVtaCabLDR: TIntegerField;
    QFcVtaCabDEPOSITO: TIntegerField;
    QFcVtaCabCALCULA_SOBRETASA: TStringField;
    QFcVtaCabDESGLOZAIVA: TStringField;
    QFcVtaCabNROENTREGA: TIntegerField;
    QFcVtaCabINGRESA_A_CTACTE: TStringField;
    QFcVtaCabINGRESA_LIBRO_IVA: TStringField;
    QFcVtaCabTIPO_REMITO: TStringField;
    QFcVtaCabIDREMITO: TIntegerField;
    QFcVtaCabREDUCIDA: TStringField;
    QFcVtaCabCOMSIONVENDEDOR: TFloatField;
    QFcVtaCabLIQUIDADA: TStringField;
    QFcVtaCabFECHA_LIQUIDACION: TSQLTimeStampField;
    QFcVtaCabVENDEDOR: TStringField;
    QFcVtaCabUSUARIO: TStringField;
    QFcVtaCabNC_CONTADO: TStringField;
    QFcVtaCabCAJA_POR_DEFECTO: TIntegerField;
    QFcVtaCabNRO_Z: TIntegerField;
    QFcVtaCabVALORES_RECIBIDOS: TFloatField;
    QFcVtaCabPERCEPCION_IB_TASA: TFloatField;
    QFcVtaCabPERCEPCION_IB_IMPORTE: TFloatField;
    QFcVtaCabPERCIBE_IB: TStringField;
    QFcVtaCabPERCEPCION_IB_BASEIMPONIBLE: TFloatField;
    QFcVtaCabRENGLONES: TSmallintField;
    QFcVtaCabFECHA_HORA: TSQLTimeStampField;
    QFcVtaCabNOTAPEDIDO_ID: TIntegerField;
    QFcVtaCabNOTAPEDIDO_NROCPBTE: TStringField;
    QFcVtaCabID_FC_CLON: TIntegerField;
    QFcVtaCabPRESUPUESTO_ID: TIntegerField;
    QFcVtaCabPRESUPUESTO_NROCPBTE: TStringField;
    QFcVtaCabMONEDA_CPBTE: TIntegerField;
    QFcVtaCabMONEDA_CPBTE_COTIZACION: TFloatField;
    QFcVtaCabPOR_CTA_Y_ORDEN: TStringField;
    QFcVtaCabPROVEEDOR: TStringField;
    QFcVtaCabTIPO_VTA: TStringField;
    QFcVtaCabID_RECEPCION_GTIA: TIntegerField;
    QFcVtaCabJURIDICION: TIntegerField;
    QFcVtaCabJURIDICION_LOCALIDAD: TIntegerField;
    QFcVtaCabCON_GTIA_EXTENDIDA: TStringField;
    QFcVtaCabMESES_DE_GARANTIA: TIntegerField;
    QFcVtaCabPOLIZA: TStringField;
    QFcVtaCabVALOR_ASEGURADO: TFloatField;
    QFcVtaCabABONO_PERIODO: TStringField;
    QFcVtaCabNUMERO_OPERACION: TStringField;
    QFcVtaCabSALDO_ACTUAL_CC: TFloatField;
    QFcVtaCabID_NOTA_CAMBIO: TIntegerField;
    QFcVtaCabCAE: TStringField;
    QFcVtaCabCAE_VENCIMIENTO: TSQLTimeStampField;
    QFcVtaCabFACTURA_ELECTRONICA: TStringField;
    QFcVtaCabCANT_BULTOS: TIntegerField;
    QFcVtaCabCUOTAS_CC: TIntegerField;
    QFcVtaCabINTERVALO_CUOTA: TIntegerField;
    QFcVtaCabID_GARANTE: TIntegerField;
    QFcVtaCabPAGO_A_CTA: TFloatField;
    QFcVtaCabID_FC_CON_ADEL: TIntegerField;
    QFcVtaCabPRIMER_VTO: TSQLTimeStampField;
    QFcVtaCabANTICIPO_VTO: TSQLTimeStampField;
    QFcVtaCabCENTRO_COSTO: TIntegerField;
    QFcVtaCabID_PEDIDO_MORPHI: TIntegerField;
    QFcVtaCabID_PAIS: TSmallintField;
    QFcVtaCabCUIT_PAIS: TStringField;
    QFcVtaCabDOC_ADUANERO: TStringField;
    QFcVtaCabFECHA_CARGA: TSQLTimeStampField;
    QFcVtaCabNRO_INTERNO: TStringField;
    QFcVtaCabFOB_TOTAL: TFloatField;
    QFcVtaCabNOTAS: TStringField;
    QFcVtaCabDESTINO_DOCUMENTO: TStringField;
    QFcVtaCabPERMISO_EMBARQUE: TStringField;
    QFcVtaCabINCOTERMS: TStringField;
    QFcVtaCabCBU: TStringField;
    QFcVtaCabASOCIADO_TIPO: TIntegerField;
    QFcVtaCabASOCIADO_PTOVTA: TIntegerField;
    QFcVtaCabASOCIADO_NRO: TFloatField;
    QFcVtaCabASOCIADO_CPTEFCH: TStringField;
    QFcVtaDet: TFDQuery;
    QFcVtaDetID: TIntegerField;
    QFcVtaDetID_CABFAC: TIntegerField;
    QFcVtaDetTIPOCPBTE: TStringField;
    QFcVtaDetCLASECPBTE: TStringField;
    QFcVtaDetNROCPBTE: TStringField;
    QFcVtaDetRENGLON: TFloatField;
    QFcVtaDetFECHAVTA: TSQLTimeStampField;
    QFcVtaDetCODIGOARTICULO: TStringField;
    QFcVtaDetDETALLE: TStringField;
    QFcVtaDetUNIDAD: TStringField;
    QFcVtaDetMODO_GRAVAMEN: TStringField;
    QFcVtaDetCANTIDAD: TFloatField;
    QFcVtaDetUNIDADES_GRAVADO: TFloatField;
    QFcVtaDetUNIDADES_EXENTO: TFloatField;
    QFcVtaDetUNIDADES_TOTAL: TFloatField;
    QFcVtaDetCOSTO_GRAVADO: TFloatField;
    QFcVtaDetCOSTO_EXENTO: TFloatField;
    QFcVtaDetCOSTO_TOTAL: TFloatField;
    QFcVtaDetUNITARIO_GRAVADO: TFloatField;
    QFcVtaDetIVA_UNITARIO: TFloatField;
    QFcVtaDetUNITARIO_EXENTO: TFloatField;
    QFcVtaDetUNITARIO_TOTAL: TFloatField;
    QFcVtaDetDESGLOZAIVA: TStringField;
    QFcVtaDetTOTAL_EXENTO: TFloatField;
    QFcVtaDetTOTAL_GRAVADO: TFloatField;
    QFcVtaDetIVA_TOTAL: TFloatField;
    QFcVtaDetTOTAL: TFloatField;
    QFcVtaDetTIPOIVA_TASA: TIntegerField;
    QFcVtaDetTIPOIVA_SOBRETASA: TIntegerField;
    QFcVtaDetIVA_TASA: TFloatField;
    QFcVtaDetIVA_SOBRETASA: TFloatField;
    QFcVtaDetDESCUENTO: TFloatField;
    QFcVtaDetDEPOSITO: TIntegerField;
    QFcVtaDetMARGEN: TFloatField;
    QFcVtaDetAFECTA_STOCK: TStringField;
    QFcVtaDetCALCULA_SOBRETASA: TStringField;
    QFcVtaDetGRAVADO_IB: TStringField;
    QFcVtaDetCON_NRO_SERIE: TStringField;
    QFcVtaDetCON_CODIGO_BARRA: TStringField;
    QFcVtaDetIB_TASA: TFloatField;
    QFcVtaDetTIPOIB_TASA: TIntegerField;
    QFcVtaDetLOTE: TIntegerField;
    QFcVtaDetPRECIO_EDITABLE: TStringField;
    QFcVtaDetID_MONEDA: TIntegerField;
    QFcVtaDetCOTIZACION: TFloatField;
    QFcVtaDetDETALLE_ADICIONAL: TStringField;
    QFcVtaDetGRUPO_DETALLE: TIntegerField;
    QFcVtaDetCTA_ORDEN_ID_RECEPCION: TIntegerField;
    QFcVtaDetCTA_ORDEN_NROCPBTE: TStringField;
    QFcVtaDetCTA_ORDEN_TIPOCPBTE: TStringField;
    QFcVtaDetCTA_ORDEN_CALSECPBTE: TStringField;
    QFcVtaDetMESES_GTIA: TIntegerField;
    QFcVtaDetCODIGOBARRA: TStringField;
    QFcVtaDetDE_PRODUCCION: TStringField;
    QFcVtaDetUNITARIO_TOTAL_OLD: TFloatField;
    QFcVtaDetUNITARIO_IVA_OLD: TFloatField;
    QFcVtaDetUNI_C_REC: TStringField;
    QFcVtaDetITEM_OCOMPRA: TIntegerField;
    QFcVtaDetCONTROL_TRAZABILIDAD: TStringField;
    QFcVtaDetCANTIDAD_UNIDADES: TFloatField;
    QFcVtaDetPRESENTACION_CANT: TFloatField;
    QFcVtaImp: TFDQuery;
    QFcVtaImpID_IMPUESTO: TIntegerField;
    QFcVtaImpID_FCVTACAB: TIntegerField;
    QFcVtaImpCODIGO_GRAVAMEN: TIntegerField;
    QFcVtaImpDETALLE: TStringField;
    QFcVtaImpNETO: TFloatField;
    QFcVtaImpTASA: TFloatField;
    QFcVtaImpIMPORTE: TFloatField;
    QComprobante: TFDQuery;
    QComprobanteID_COMPROBANTE: TIntegerField;
    QComprobanteTIPO_COMPROB: TStringField;
    QComprobanteCLASE_COMPROB: TStringField;
    QComprobanteDENOMINACION: TStringField;
    QComprobanteSUCURSAL: TIntegerField;
    QComprobanteLETRA: TStringField;
    QCajaMov: TFDQuery;
    QCajaMovID_MOV_CAJA: TIntegerField;
    QCajaMovID_CAJA: TIntegerField;
    QCajaMovFECHA_CAJA: TSQLTimeStampField;
    QCajaMovFECHA_OPERACION: TSQLTimeStampField;
    QCajaMovTIPO_OPERACION: TStringField;
    QCajaMovTIPO_COMPROB: TStringField;
    QCajaMovCLASE_COMPROB: TStringField;
    QCajaMovID_COMPROBANTE: TIntegerField;
    QCajaMovNRO_COMPROBANTE: TStringField;
    QCajaMovHABER: TFloatField;
    QCajaMovDEBE: TFloatField;
    QCajaMovID_TPAGO: TIntegerField;
    QCajaMovID_FPAGO: TIntegerField;
    QCajaMovUNIDADES: TFloatField;
    QCajaMovCOTIZACION: TFloatField;
    QCajaMovID_CUENTA_CAJA: TIntegerField;
    QCajaMovMONEDA: TIntegerField;
    QMovTCredito: TFDQuery;
    QMovTCreditoID_MOV_TC: TIntegerField;
    QMovTCreditoID_CAJA: TIntegerField;
    QMovTCreditoID_MOV_CAJA: TIntegerField;
    QMovTCreditoID_FPAGO: TIntegerField;
    QMovTCreditoID_TC: TIntegerField;
    QMovTCreditoFECHA: TSQLTimeStampField;
    QMovTCreditoTITULAR: TStringField;
    QMovTCreditoCAN_CUOTAS: TIntegerField;
    QMovTCreditoN_DOCU: TStringField;
    QMovTCreditoUNIDADES: TFloatField;
    QMovTCreditoCOTIZACION: TFloatField;
    QMovTCreditoIMPORTE: TFloatField;
    QMovTCreditoOTROS: TStringField;
    QMovTCreditoMONEDA: TIntegerField;
    QMovTCreditoID_CUENTA_CAJA: TIntegerField;
    QMovTCreditoUNIDADES_NETO: TFloatField;
    QMovTCreditoIMPORTE_NETO: TFloatField;
    QMovTCreditoCOEFICIENTE: TFloatField;
    QMovTCreditoVALORCUOTA: TFloatField;
    QMovTCreditoIMPORTE_RECARGO: TFloatField;
    QMovTCreditoID_CUENTA_BANCO: TIntegerField;
    QMovTCreditoNRO_CUPON: TIntegerField;
    QMovTCreditoFECHA_ACREDITACION: TSQLTimeStampField;
    QMovTCreditoACREDITADA: TStringField;
    QMovTCreditoLOTE: TStringField;
    QMovTCreditoTERMINAL: TStringField;
    QMovTCreditoSALDO_IMPORTE: TFloatField;
    QMovEfectivo: TFDQuery;
    QMovEfectivoID_EFECTIVO: TIntegerField;
    QMovEfectivoID_CAJA: TIntegerField;
    QMovEfectivoID_MOV_CAJA: TIntegerField;
    QMovEfectivoID_FPAGO: TIntegerField;
    QMovEfectivoCOTIZACION: TFloatField;
    QMovEfectivoUNIDADES: TFloatField;
    QMovEfectivoIMPORTE: TFloatField;
    QMovEfectivoID_CUENTA_CAJA: TIntegerField;
    QMovEfectivoMONEDA: TIntegerField;
    QChe3: TFDQuery;
    QChe3ID_CHEQUE_TER: TIntegerField;
    QChe3ID_CAJA: TIntegerField;
    QChe3ID_MOV_CAJA: TIntegerField;
    QChe3ID_FPAGO: TIntegerField;
    QChe3ID_BANCO: TIntegerField;
    QChe3NUMERO: TIntegerField;
    QChe3FECHA_EMISION: TSQLTimeStampField;
    QChe3FECHA_COBRO: TSQLTimeStampField;
    QChe3FECHA_ENTRADA: TSQLTimeStampField;
    QChe3FECHA_SALIDA: TSQLTimeStampField;
    QChe3ORIGEN: TStringField;
    QChe3DESTINO: TStringField;
    QChe3UNIDADES: TFloatField;
    QChe3IMPORTE: TFloatField;
    QChe3DISPONIBLE: TStringField;
    QChe3FIRMANTE: TStringField;
    QChe3COTIZACION: TFloatField;
    QChe3ID_MOV_CAJA_EGRESOS: TIntegerField;
    QChe3ID_CUENTA_CAJA: TIntegerField;
    QChe3ID_CUENTA_BCO_DEPOSITADO: TIntegerField;
    QChe3MONEDA: TIntegerField;
    QChe3SALDO_UNIDADES: TFloatField;
    QChe3SALDO_IMPORTE: TFloatField;
    QChe3CUIT: TStringField;
    QChe3SUCURSAL_BCO: TStringField;
    QChe3NRO_CTA: TStringField;
    QBuscaSucursal: TFDQuery;
    QAjusteCab: TFDQuery;
    QAjusteCabID_RTO: TIntegerField;
    QAjusteCabFECHA: TSQLTimeStampField;
    QAjusteCabLETRA: TStringField;
    QAjusteCabSUCRTO: TStringField;
    QAjusteCabNUMRTO: TStringField;
    QAjusteCabSUCURSAL: TIntegerField;
    QAjusteCabNROCPBTE: TStringField;
    QAjusteCabTIPOCPBTE: TStringField;
    QAjusteCabCLASECPBTE: TStringField;
    QAjusteCabOBS: TStringField;
    QAjusteCabDEPOSITO: TIntegerField;
    QAjusteCabAJUSTE_CERO_STOCK: TStringField;
    QAjusteCabUSUARIO: TStringField;
    QAjusteCabFECHA_HORA: TSQLTimeStampField;
    QAjusteCabTOTAL: TFloatField;
    QAjusteCabTOTAL_VTA: TFloatField;
    QAjusteCabLISTAPRECIO: TIntegerField;
    QAjusteCabMOTIVO: TIntegerField;
    QAjusteCabID_INVENTARIO: TIntegerField;
    QAjusteCabPERSONAL_RETIRA: TStringField;
    QAjusteCabMUESTRACOMPROBANTE: TStringField;
    QAjusteCabID_TIPOCOMPROBANTE: TIntegerField;
    QAjusteCabMUESTRASUCURSAL: TStringField;
    QAjusteCabMUESTRADEPOSITO: TStringField;
    QAjusteDet: TFDQuery;
    QAjusteDetID_RTO_DET: TIntegerField;
    QAjusteDetID_RTO_CAB: TIntegerField;
    QAjusteDetFECHA: TSQLTimeStampField;
    QAjusteDetCODIGO: TStringField;
    QAjusteDetDETALLE: TStringField;
    QAjusteDetUNIDAD: TStringField;
    QAjusteDetCANTIDAD: TFloatField;
    QAjusteDetNROCPBTE: TStringField;
    QAjusteDetDEPOSITO: TIntegerField;
    QAjusteDetCLASECPBTE: TStringField;
    QAjusteDetTIPOCPBTE: TStringField;
    QAjusteDetAFECTASTOCK: TStringField;
    QAjusteDetSTOCK_ACTUAL_COMPRA: TFloatField;
    QAjusteDetSTOCK_ACTUAL_VTA: TFloatField;
    QAjusteDetCON_NRO_SERIE: TStringField;
    QAjusteDetCOSTO_UNITARIO: TFloatField;
    QAjusteDetCOSTO_TOTAL: TFloatField;
    QAjusteDetPRECIO_UNITARIO: TFloatField;
    QAjusteDetPRECIO_TOTAL: TFloatField;
    QAjusteDetCONTROL_TRAZABILIDAD: TStringField;
    QAjusteDetUNIDADES_STK: TFloatField;
    QAjusteDetPRESENT_CANTIDAD: TFloatField;
    QBuscaSucursalCODIGO: TIntegerField;
    QBuscaSucursalDETALLE: TStringField;
    QAjusteSubDetalle: TFDQuery;
    QAjusteSubDetalleID: TIntegerField;
    QAjusteSubDetalleID_RTODET: TIntegerField;
    QAjusteSubDetalleID_RTOCAB: TIntegerField;
    QAjusteSubDetalleTIPOCPBTE: TStringField;
    QAjusteSubDetalleCLASECPBTE: TStringField;
    QAjusteSubDetalleFECHA: TSQLTimeStampField;
    QAjusteSubDetalleNROCPBTE: TStringField;
    QAjusteSubDetalleCODIGOARTICULO: TStringField;
    QAjusteSubDetalleSERIE: TStringField;
    QAjusteSubDetalleDEPOSITO: TIntegerField;
    QAjusteSubDetalleTIPO: TStringField;
    QDebitos: TFDQuery;
    QDebitosID: TIntegerField;
    QDebitosID_MOV_CAJA: TIntegerField;
    QDebitosID_CAJA: TIntegerField;
    QDebitosID_FPAGO: TIntegerField;
    QDebitosNUMERO: TIntegerField;
    QDebitosID_CUENTA_CAJA: TIntegerField;
    QDebitosID_CUENTA_BANCO: TIntegerField;
    QDebitosMONEDA: TIntegerField;
    QDebitosUNIDADES: TFloatField;
    QDebitosIMPORTE: TFloatField;
    QDebitosORIGEN: TStringField;
    QDebitosFECHA: TSQLTimeStampField;
    QDebitosCOTIZACION: TFloatField;
    QDebitosMUESTRACTACAJA: TStringField;
    QTransBco: TFDQuery;
    QTransBcoID: TIntegerField;
    QTransBcoID_MOV_CAJA: TIntegerField;
    QTransBcoID_CAJA: TIntegerField;
    QTransBcoID_FPAGO: TIntegerField;
    QTransBcoNUMERO: TIntegerField;
    QTransBcoID_CUENTA_CAJA: TIntegerField;
    QTransBcoID_CUENTA_BANCO: TIntegerField;
    QTransBcoMONEDA: TIntegerField;
    QTransBcoUNIDADES: TFloatField;
    QTransBcoIMPORTE: TFloatField;
    QTransBcoORIGEN: TStringField;
    QTransBcoFECHA: TSQLTimeStampField;
    QTransBcoCOTIZACION: TFloatField;
    QTransBcoMUESTRACTACAJA: TStringField;
    QComprobanteAjustes: TFDQuery;
    DSComprobanteAjustes: TDataSource;
    QComprobanteAjustesID_COMPROBANTE: TIntegerField;
    QComprobanteAjustesTIPO_COMPROB: TStringField;
    QComprobanteAjustesCLASE_COMPROB: TStringField;
    QComprobanteAjustesDENOMINACION: TStringField;
    QComprobanteAjustesSUCURSAL: TIntegerField;
    QComprobanteAjustesLETRA: TStringField;
    QFcVtaCabTOTAL_CALCULADO: TFloatField;
    FDGUIxWaitCursor1: TFDGUIxWaitCursor;
    FDPhysFBDriverLink1: TFDPhysFBDriverLink;
    QFcVtaCabFECHAVTA: TSQLTimeStampField;
    QFcVtaCabFECHAVTO: TSQLTimeStampField;
    QFcVtaCabFECHA_FISCAL: TSQLTimeStampField;
    QMax: TFDQuery;
    QMin: TFDQuery;
    QMaxMAX: TIntegerField;
    QMinMIN: TIntegerField;
    XQFcVtaCab: TXDataset;
    RDConnection: TRemoteDBDatabase;
    XQFcVtaDet: TXDataset;
    XQFcVtaImp: TXDataset;
    XQComprobante: TXDataset;
    XDataset4: TXDataset;
    XDataset5: TXDataset;
    XDataset6: TXDataset;
    procedure QFcVtaCabCalcFields(DataSet: TDataSet);
    procedure QFcVtaDetUNITARIO_TOTALGetText(Sender: TField; var Text: string;
      DisplayText: Boolean);
    procedure QFcVtaDetTOTALGetText(Sender: TField; var Text: string;
      DisplayText: Boolean);
    procedure DataModuleDestroy(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DatosImportacion: TDatosImportacion;

implementation

{$R *.dfm}

procedure TDatosImportacion.DataModuleDestroy(Sender: TObject);
begin
  DatosImportacion:=nil;
end;

procedure TDatosImportacion.QFcVtaCabCalcFields(DataSet: TDataSet);
begin
  QFcVtaCabTOTAL_CALCULADO.Value:=QFcVtaCabTOTAL.Value;
  if QFcVtaCabTIPOCPBTE.Value='NC' then
    QFcVtaCabTOTAL_CALCULADO.Value:=QFcVtaCabTOTAL.Value * -1;

end;

procedure TDatosImportacion.QFcVtaDetTOTALGetText(Sender: TField;
  var Text: string; DisplayText: Boolean);
begin
  Text:=FormatFloat(',0.00;-,0.00;-',QFcVtaDetTOTAL.Value);
  if QFcVtaDetDESGLOZAIVA.Value='N' then
    Text:= FormatFloat(',0.00;-,0.00;-', (QFcVtaDetTOTAL.Value + QFcVtaDetIVA_TOTAL.Value));


end;

procedure TDatosImportacion.QFcVtaDetUNITARIO_TOTALGetText(Sender: TField;
  var Text: string; DisplayText: Boolean);
begin
  Text:=FormatFloat(',0.00;-,0.00;-', QFcVtaDetUNITARIO_TOTAL.Value);
  if QFcVtaDetDESGLOZAIVA.Value='N' then
    Text:= FormatFloat(',0.00;-,0.00;-', QFcVtaDetUNITARIO_TOTAL.Value + QFcVtaDetIVA_UNITARIO.Value);

end;

end.
