program Menu;
uses
  windows,
  Forms,
  VirtualUI_AutoRun,
  MidasLib,
  UMenu in 'UMenu.pas' {FMenu},
  UAcercaDe in 'UAcercaDe.pas' {FormAcercaDe},
  DMClientes in 'DMClientes.pas' {DatosClientes: TDataModule},
  DMCompra in 'DMCompra.pas' {DatosCompra: TDataModule},
  DMProveedores in 'DMProveedores.pas' {DatosProveedores: TDataModule},
  DMStock in 'DMStock.pas' {DatosStock: TDataModule},
  DMVenta in 'DMVenta.pas' {DatosVentas: TDataModule},
  DMRecibos in 'DMRecibos.pas' {DatosRecibos: TDataModule},
  DMVentaCtdo in 'DMVentaCtdo.pas' {DatosVentasCtdo: TDataModule},
  UBuscadorCpbte in 'UBuscadorCpbte.pas' {FormBuscaCpbte},
  ComposicionPrecio in 'ComposicionPrecio.pas' {FormComposicionPrecio},
  DMCompraCtdo in 'DMCompraCtdo.pas' {DatosCompraCtdo: TDataModule},
  DMPresupuesto in 'DMPresupuesto.pas' {DatosPresupuesto: TDataModule},
  UCtaCteCompra in 'UCtaCteCompra.pas' {FormCtaCteCompra},
  DMOPagos in 'DMOPagos.pas' {DatosOPago: TDataModule},
  UCarteraCheques in 'UCarteraCheques.pas' {FormCarteraCheques},
  UCtaCteVta in 'UCtaCteVta.pas' {FormCtaCteVta},
  USaldosClientes in 'USaldosClientes.pas' {FormSaldosClientes},
  USaldosProveedores in 'USaldosProveedores.pas' {FormSaldosProveedores},
  UConsultaArticuloVendido in 'UConsultaArticuloVendido.pas' {FormArticulosVendidos},
  UPlanillaCheTercero in 'UPlanillaCheTercero.pas' {FormPlanillaCheTercero},
  UCaja in 'UCaja.pas' {FormCaja},
  UCambioPrecio in 'UCambioPrecio.pas' {FormCambioPrecios},
  UBuscarPresupuestos in 'UBuscarPresupuestos.pas' {FormBuscarPresupuestos},
  UListaPreciosPersonalizada in 'UListaPreciosPersonalizada.pas' {FormListaPreciosPersonalizada},
  URetenciones in 'URetenciones.pas' {FormRetenciones},
  UEmpresa in 'UEmpresa.pas' {FormEmpresa},
  UConsultaStock in 'UConsultaStock.pas' {FormConsultaStock},
  UPresentacion in 'UPresentacion.pas' {FormPresentacion},
  UABMBase in 'UABMBase.pas' {FormABMBase},
  UGastosRubros in 'UGastosRubros.pas' {FormGastosRubro},
  UComprobantes in 'UComprobantes.pas' {FormComprobantes},
  UMovValoresIngreso in 'UMovValoresIngreso.pas' {FrameMovValoresIngreso: TFrame},
  UEgresoCaja in 'UEgresoCaja.pas' {FormEgresoCaja},
  UGastosCuentas in 'UGastosCuentas.pas' {FormGastosCuentas},
  ULocalidades in 'ULocalidades.pas' {FormLocalidades},
  UAlicuotasIva in 'UAlicuotasIva.pas' {FormAlicuotasIva},
  UAperturaCaja in 'UAperturaCaja.pas' {FormAperturaCaja},
  UAjustesCCProveedores in 'UAjustesCCProveedores.pas' {FormAjusteCCProveedores},
  UInformeVta in 'UInformeVta.pas' {FormInformeVta},
  USucursal in 'USucursal.pas' {FormSucursal},
  UTransferencia in 'UTransferencia.pas' {FormTransferencias},
  UOPago_2 in 'UOPago_2.pas' {FormOPago_2},
  UCompraCtdo_2 in 'UCompraCtdo_2.pas' {FormCompraCtdo_2},
  UFacturaCtdo_2 in 'UFacturaCtdo_2.pas' {FormCpbteCtdo_2},
  UClientes_2 in 'UClientes_2.pas' {FormClientes_2},
  UProveedor_2 in 'UProveedor_2.pas' {FormProveedor_2},
  UStock_2 in 'UStock_2.pas' {FormStock_2},
  UMarcas_2 in 'UMarcas_2.pas' {FormMarca_2},
  URubro_2 in 'URubro_2.pas' {FormRubro_2},
  USubRubro_2 in 'USubRubro_2.pas' {FormSubRubros_2},
  UDepositos_2 in 'UDepositos_2.pas' {FormDepositos_2},
  UPresupuesto_2 in 'UPresupuesto_2.pas' {FormPresupuesto_2},
  UControlNumeracion in 'UControlNumeracion.pas' {FormControlNumeracion},
  UAplicacionesCCCompra_2 in 'UAplicacionesCCCompra_2.pas' {FormAplicacionesCCCompra_2},
  UControlCtaCte in 'UControlCtaCte.pas' {FormControlCC},
  URecibo_2 in 'URecibo_2.pas' {FormRecibo_2},
  UAplicacionesCCVta_2 in 'UAplicacionesCCVta_2.pas' {FormAplicacionesCCVta_2},
  UControlCalculoImpuesto in 'UControlCalculoImpuesto.pas' {FormControlImpuestos},
  UMovValoresEgresos in 'UMovValoresEgresos.pas' {FrameMovValoresEgresos: TFrame},
  UInscripcion_2 in 'UInscripcion_2.pas' {FormInscripcion_2},
  UCompra_2 in 'UCompra_2.pas' {FormCompra_2},
  UGraficoVentas in 'UGraficoVentas.pas' {FormGraficoVentas},
  UPercepcionIB_2 in 'UPercepcionIB_2.pas' {FormPercepcionIB_2},
  UPercepcionIva_2 in 'UPercepcionIva_2.pas' {FormPercepcionIva_2},
  UTarjetaCredito_2 in 'UTarjetaCredito_2.pas' {FormTCredito_2},
  UChequeras_2 in 'UChequeras_2.pas' {FormChequeras_2},
  UCtaCaja_2 in 'UCtaCaja_2.pas' {FormCtaCaja_2},
  UFPago_2 in 'UFPago_2.pas' {FormFormaPago_2},
  UBancos_2 in 'UBancos_2.pas' {FormBancos_2},
  UAjustesCCClientes_2 in 'UAjustesCCClientes_2.pas' {FormAjustesCCVenta_2},
  URentabilidad in 'URentabilidad.pas' {FormRentabilidad},
  URelacionPagoVencimientoClientes in 'URelacionPagoVencimientoClientes.pas' {FormRelacionPagoSClientes},
  UAnalisisCreditoCliente in 'UAnalisisCreditoCliente.pas' {FormAnalisisCreditoCliente},
  UAjusteMercaderia in 'UAjusteMercaderia.pas' {FormAjustesStock},
  UTRetenciones in 'UTRetenciones.pas' {FormTRetenciones},
  UVtaArticulosExentos in 'UVtaArticulosExentos.pas' {FormArticulosExentosVendidos},
  URemitos in 'URemitos.pas' {FormRemitos},
  DMRemitos in 'DMRemitos.pas' {DatosRemitos: TDataModule},
  UAgenda in 'UAgenda.pas' {FormAgenda},
  UCondicionPago in 'UCondicionPago.pas' {FormCondicionPago},
  UProvincia in 'UProvincia.pas' {FormProvincia},
  UZona in 'UZona.pas' {FormZonas},
  UGastosBancarios in 'UGastosBancarios.pas' {FormMovEgr_IngBancos},
  UConceptosBancarios in 'UConceptosBancarios.pas' {FormConceptosBancarios},
  UDepositosBancarios in 'UDepositosBancarios.pas' {FormDepositosBancarios},
  UResumenBco in 'UResumenBco.pas' {FormResumenBco},
  UBuscadorBoletaDeposito in 'UBuscadorBoletaDeposito.pas' {FormBuscadorBoletaDepositos},
  UTransferenciaEfectivo in 'UTransferenciaEfectivo.pas' {FormTransferenciaEfectivo},
  UTransferenciaCh3 in 'UTransferenciaCh3.pas' {FormTransferenciaChe3},
  UControlCalculoImpuestoCompra in 'UControlCalculoImpuestoCompra.pas' {FormControlImpuestoCompra},
  UCargos in 'UCargos.pas' {FormCargos},
  UPersonal in 'UPersonal.pas' {FormPersonal},
  UAplicacionesNCCompra in 'UAplicacionesNCCompra.pas' {FormAplicacionesNCCompra},
  UAplicacionesNCVenta in 'UAplicacionesNCVenta.pas' {FormAplicacionesNCVta},
  UPlanCuentaDeGastos in 'UPlanCuentaDeGastos.pas' {FormPlanCuentaGastos},
  UAdelantosSueldos in 'UAdelantosSueldos.pas' {FormAdelantosSueldo},
  USaldosGastos in 'USaldosGastos.pas' {FormSaldoGastos},
  UChequesACaja in 'UChequesACaja.pas' {FormCheACaja},
  UMoneda in 'UMoneda.pas' {FormMonedas},
  UOpciones in 'UOpciones.pas' {FormOpciones},
  UIngresoCaja in 'UIngresoCaja.pas' {FormIngresoCaja},
  UMuestraOPago in 'UMuestraOPago.pas' {FormMuestraOPago},
  UChequesEmitidos in 'UChequesEmitidos.pas' {FormChequesEmitidos},
  UMuestraChe3 in 'UMuestraChe3.pas' {FormMuestraChe3},
  UMuestraCheEmitidos in 'UMuestraCheEmitidos.pas' {FormMuestraCheEmitidos},
  UConsultaExistencia in 'UConsultaExistencia.pas' {FormExistencias},
  UControlCierreFiscal in 'UControlCierreFiscal.pas' {FormCierresFiscales},
  UCambioPrecio_2 in 'UCambioPrecio_2.pas' {FormCambioPrecio_2},
  UVentaPorCliente in 'UVentaPorCliente.pas' {FormVentaPorCliente},
  UVtaPorClienteProducto in 'UVtaPorClienteProducto.pas' {FormVtaClienteProducto},
  UFacturarRemitos in 'UFacturarRemitos.pas' {FormFacturarRemitos},
  UBuscaDirectorio in 'UBuscaDirectorio.pas' {FormBuscaDirectorio},
  UConfiguraIni in 'UConfiguraIni.pas' {FormConfiguraIni},
  UListaPresupuestos in 'UListaPresupuestos.pas' {FormListaPresupuestos},
  UBuscaCajasCerradas in 'UBuscaCajasCerradas.pas' {FormBuscaCajasCerradas},
  UUnidades in 'UUnidades.pas' {FormUnidades},
  UControladorCaja in 'UControladorCaja.pas' {FormControlCaja},
  UControlComprobantesNoImpresos in 'UControlComprobantesNoImpresos.pas' {FormControlCompNoImpresos},
  UCtaCteEmpleados in 'UCtaCteEmpleados.pas' {FormCtaCteEmpleados},
  UIngresosCtaEmpleados in 'UIngresosCtaEmpleados.pas' {FormIngresoEmpleados},
  UBuscadorIngresosCtaEmpleados in 'UBuscadorIngresosCtaEmpleados.pas' {FormBuscadorIngresosEmpleados},
  UControlComisiones in 'UControlComisiones.pas' {FormControlComisiones},
  UListadoCheEmitidos in 'UListadoCheEmitidos.pas' {FormListadoCheEmitidos},
  UControlAsignaVendedor in 'UControlAsignaVendedor.pas' {FormAsignacionVendedor},
  UListadoFcPorVendedor in 'UListadoFcPorVendedor.pas' {FormFacturaPorVendedor},
  UControlAperturaCaja in 'UControlAperturaCaja.pas' {FormControlAperturaCaja},
  USaldoClientesMensual in 'USaldoClientesMensual.pas' {FormSaldoClientesMensual},
  UCorrectorDecimales in 'UCorrectorDecimales.pas' {FormCorrectorDecimales},
  UManejadorTrigger in 'UManejadorTrigger.pas' {FormManejadorTriggers},
  UFacturarRemitosAgrupados in 'UFacturarRemitosAgrupados.pas' {FormFacturaRemitoAgrupado},
  USaldoProveedoresMensual in 'USaldoProveedoresMensual.pas' {FormSaldoProveedorMensual},
  UListadoArtGravEnIngBrutosVentas in 'UListadoArtGravEnIngBrutosVentas.pas' {FormListadoArtGravIngBrutosVentas},
  UListadoPercepciones in 'UListadoPercepciones.pas' {FormListaPercepciones},
  UFacModelo in 'UFacModelo.pas' {FormFacModelo},
  DMFacModelo in 'DMFacModelo.pas' {DatosModelo: TDataModule},
  UFacturarModelos in 'UFacturarModelos.pas' {FormFacturarModelos},
  UGrupoModelo in 'UGrupoModelo.pas' {FormGrupoModelo},
  UOrdenCompra in 'UOrdenCompra.pas' {FormOrdenCompra},
  DMOrdenCompra in 'DMOrdenCompra.pas' {DatosOrdenCompra: TDataModule},
  UPreciosEspecialesClientes in 'UPreciosEspecialesClientes.pas' {FormPreciosEspecialesClientes},
  UAjusteStockCero in 'UAjusteStockCero.pas' {FormAjusteStockCero},
  UAnalisisIngresosEgresos in 'UAnalisisIngresosEgresos.pas' {FormAnalisisEgresosIngresos},
  UDatosClienteCabeceraCpbte in 'UDatosClienteCabeceraCpbte.pas' {FormDatosClienteCabeceraCpbte},
  URemplazoCheques in 'URemplazoCheques.pas' {FormRemplazoCheques},
  UMuestraDepositos in 'UMuestraDepositos.pas' {FormMuestraDepositos},
  UCorrectorDeCero in 'UCorrectorDeCero.pas' {FormCorrectorCeros},
  UComparacionCompraVenta in 'UComparacionCompraVenta.pas' {FormRelacionCompraVenta},
  UStockProduccion in 'UStockProduccion.pas' {FormStockProduccion},
  UCostosFijos in 'UCostosFijos.pas' {FormCostosFijos},
  UOrdenProduccion in 'UOrdenProduccion.pas' {FormOrdenProduccion},
  UOProduccionProceso in 'UOProduccionProceso.pas' {FormOProduccionProcesando},
  UOProduccionIniciada in 'UOProduccionIniciada.pas' {FormOProduccionIniciadas},
  UOCompraAutorizacion in 'UOCompraAutorizacion.pas' {FormOCompraAutorizar},
  UOCompraRecepcion in 'UOCompraRecepcion.pas' {FormOCompraRecepcion},
  UOCompraImpresion in 'UOCompraImpresion.pas' {FormOCompraImpresion},
  UCategoriaProductos in 'UCategoriaProductos.pas' {FormCategoriaProductos},
  UProductos in 'UProductos.pas' {FormProductos},
  UOrdenDeTrabajo in 'UOrdenDeTrabajo.pas' {FormOrdenDeTrabajo},
  DMOrdenTrabajo in 'DMOrdenTrabajo.pas' {DatosOrdenDeTrabajo: TDataModule},
  UTransportes in 'UTransportes.pas' {FormTransportes},
  UOCompraNuevas in 'UOCompraNuevas.pas' {FormOCompraNuevas},
  UOCompraRealizadas in 'UOCompraRealizadas.pas' {FormOCompraRealizadas},
  UControlCpbteEmitidos in 'UControlCpbteEmitidos.pas' {FormControlCpbteEmitidos},
  UGraficoIntegrado in 'UGraficoIntegrado.pas' {FormGraficoIntegrado},
  UListadoRecibos in 'UListadoRecibos.pas' {FormListadoRecibos},
  UAnalisiCobranza in 'UAnalisiCobranza.pas' {FormAnalisisCobranza},
  ULstCompraPorRubro in 'ULstCompraPorRubro.pas' {FormListadoCompraPorRubro},
  UPlanRubo_SubRubro_Stock in 'UPlanRubo_SubRubro_Stock.pas' {FormPlanRubro_SubRubro_Stock},
  ULibroIvaBase in 'ULibroIvaBase.pas' {FormLibroIvaBase},
  ULibroIvaCompra_2 in 'ULibroIvaCompra_2.pas' {FormLibroIvaCompra_2},
  ULibroIvaVenta_2 in 'ULibroIvaVenta_2.pas' {FormLibroIvaVenta_2},
  UListadoOtPuntaje in 'UListadoOtPuntaje.pas' {FormMovimientosPuntaje},
  ULstOTrabajoArchivada in 'ULstOTrabajoArchivada.pas' {FormOrdenTrabajoArchivadas},
  UListadoOTPorCliente_ConDetalle in 'UListadoOTPorCliente_ConDetalle.pas' {FormOrdenesTrabajoPorClienteDetalle},
  URubrosProveedores in 'URubrosProveedores.pas' {FormRubrosProveedores},
  ULogin in 'ULogin.pas' {FormLogin},
  UListadoMovCaja in 'UListadoMovCaja.pas' {FormListadoMovCaja},
  UExportadorFcComp in 'UExportadorFcComp.pas' {FormExportarFcComp},
  UImportarFcComp in 'UImportarFcComp.pas' {FormImportarFcComp},
  UAsignarCodigoBarra in 'UAsignarCodigoBarra.pas' {FormAsignaCodigoBarra},
  UCajaUser in 'UCajaUser.pas' {FormAsignaCajaUsuario},
  UExportaArticulos in 'UExportaArticulos.pas' {FormExportaStock},
  UImportarStock in 'UImportarStock.pas' {FormImportarStock},
  UExportadorFcVta in 'UExportadorFcVta.pas' {FormExportaFcVta_XML},
  UImportarFcVta in 'UImportarFcVta.pas' {FormImportarFcVta},
  UExpotadorClientes in 'UExpotadorClientes.pas' {FormExportarClientes},
  UImportarClientes in 'UImportarClientes.pas' {FormImportarClientes},
  UImportarProveedores in 'UImportarProveedores.pas' {FormImportarProveedores},
  UExpotadorProveedores in 'UExpotadorProveedores.pas' {FormExportaProveedores},
  UNotaPedido in 'UNotaPedido.pas' {FormNotaPedido},
  URelacionStockProveedor in 'URelacionStockProveedor.pas' {FormRelacionStockProveedor},
  UDetalleDeNotaPedido in 'UDetalleDeNotaPedido.pas' {FormDetallesNotaPedido},
  UBuscaProveedorStock in 'UBuscaProveedorStock.pas' {FormBuscaProveedorStock},
  UMovStockPorDeposito in 'UMovStockPorDeposito.pas' {FormMovTransferenciaStock},
  UCronogramaOT in 'UCronogramaOT.pas' {FormCronogramaOT},
  UMovPorProductos in 'UMovPorProductos.pas' {FormMovProductos},
  UListaPrecioEspecial in 'UListaPrecioEspecial.pas' {FormListaPrecioEspecial},
  UListadoOPago in 'UListadoOPago.pas' {FormListadoOPago},
  UListadoOTrabajoEmpleados in 'UListadoOTrabajoEmpleados.pas' {FormListadoOTrabajoEmpleados},
  UControlUnidadesStock in 'UControlUnidadesStock.pas' {FormControlUnidadesStock},
  UListadoDepositosBancarios in 'UListadoDepositosBancarios.pas' {FormListadoDepositoBco},
  UComparacionPrecios in 'UComparacionPrecios.pas' {FormComparativaPrecios},
  UArticulosAModificarPrecio in 'UArticulosAModificarPrecio.pas' {FormArticulosAModificarPrecio},
  ULogFile in 'ULogFile.pas' {FormLog},
  URemplazoChequesTercero in 'URemplazoChequesTercero.pas' {FormRemplazoChequesTerceros},
  UListadoMovimientosStock in 'UListadoMovimientosStock.pas' {FormListadoMovStock},
  UInventario in 'UInventario.pas' {FormInventario},
  UConsultaStockXSerie in 'UConsultaStockXSerie.pas' {FormConsultaXSerie},
  UBuscaArticuloSerie in 'UBuscaArticuloSerie.pas' {FormArticulosSeries},
  UListadoPoliticaPrecios in 'UListadoPoliticaPrecios.pas' {FormListaPoliticasPrecios},
  UBuscadorClientes in 'UBuscadorClientes.pas' {FormBuscadorClientes},
  UBuscadorArticulos in 'UBuscadorArticulos.pas' {FormBuscadorArticulos},
  UComprometido in 'UComprometido.pas' {FormStockComprometido},
  UControlMovStockVta in 'UControlMovStockVta.pas' {FormControlMovStockVta},
  URemplazoSeries in 'URemplazoSeries.pas' {FormRemplazoSeries},
  UBuscadorSeries in 'UBuscadorSeries.pas' {FormBuscadorSeries},
  UComisionesVendedores in 'UComisionesVendedores.pas' {FormComisionesVendedores},
  UControlComisionesPorArticulo in 'UControlComisionesPorArticulo.pas' {FormControlComisionesPorArticulo},
  UUltimaVtaCliente in 'UUltimaVtaCliente.pas' {FormUltimaVta},
  URecepcionMercaderia in 'URecepcionMercaderia.pas' {FormRecepcionMercaderia},
  DMRecepMerca in 'DMRecepMerca.pas' {DatosRecepMerca: TDataModule},
  UBuscarRecepcionesPendientes in 'UBuscarRecepcionesPendientes.pas' {FormBuscarRecepcionesPendientes},
  UResumenMovStock in 'UResumenMovStock.pas' {FormResumenMovStock},
  UListadoCostoArtVenta in 'UListadoCostoArtVenta.pas' {FormListadoCostoArtVendidos},
  UListadoVtaRubro_SubRubro in 'UListadoVtaRubro_SubRubro.pas' {FormListadoVtaRubro},
  UListadoSaldosEmpleados in 'UListadoSaldosEmpleados.pas' {FormSaldosEmpleados},
  USaldoIngresos in 'USaldoIngresos.pas' {FormSaldoIngresos},
  UControlCantidadesStock in 'UControlCantidadesStock.pas' {FormControlCantidadesStock},
  UJuridiccion in 'UJuridiccion.pas' {FormJuridiccion},
  UAdministradorSeries in 'UAdministradorSeries.pas' {FormAdministradorSeries},
  UReasignaCtaGastoIngreso in 'UReasignaCtaGastoIngreso.pas' {FormReasignaCtasGastosIngresos},
  UComprobantesUsuarios in 'UComprobantesUsuarios.pas' {FormComprobantesUsuarios},
  UTasaRetGanancias in 'UTasaRetGanancias.pas' {FormTasaRetGanancia},
  UAjustesSeries in 'UAjustesSeries.pas' {FormAjustesSeries},
  UListadoRetencionesGanamcia in 'UListadoRetencionesGanamcia.pas' {FormListadoRetencionesGanancias},
  UFtp in 'UFtp.pas' {FormFTP},
  UCorreo in 'UCorreo.pas' {FormCorreo},
  UBuscadorTipoComprobante in 'UBuscadorTipoComprobante.pas' {FormBuscadorComprobantes},
  UAnulacionOPago in 'UAnulacionOPago.pas' {FormAnulacionOPago},
  DMAnulacionOPagos in 'DMAnulacionOPagos.pas' {DatosAnulacionOPago: TDataModule},
  UBuscadorChePropios in 'UBuscadorChePropios.pas' {FormBuscadorChePropios},
  UAnulacionChequesPropios in 'UAnulacionChequesPropios.pas' {FormAnulaCheques},
  UAvisoProceso in 'UAvisoProceso.pas' {FormProceso},
  UListadoTransfBanco in 'UListadoTransfBanco.pas' {FormListadoTransfBanco},
  UListadoDebitosBco in 'UListadoDebitosBco.pas' {FormListadoDebitosBco},
  UListadoDebitos in 'UListadoDebitos.pas' {FormListadoDebitos},
  UAnulacionRecibos in 'UAnulacionRecibos.pas' {FormAnulacionRecibos},
  DMAnulacionRecibos in 'DMAnulacionRecibos.pas' {DatosAnulacionRecibo: TDataModule},
  UDetalleArticulosVendidos in 'UDetalleArticulosVendidos.pas' {FormDetalleArticulosVendidos},
  ULstVtaSucursalDeCliente in 'ULstVtaSucursalDeCliente.pas' {FormListadoVta_SucursalCliente},
  UTasaRetIIBB in 'UTasaRetIIBB.pas' {FormTasaRetIIBB},
  UStockPendiente in 'UStockPendiente.pas' {FormStockPendiente},
  UListadoRetencionesCobranza in 'UListadoRetencionesCobranza.pas' {FormListadoRetencionesCobranza},
  UListadoRetencionesPagos_IB in 'UListadoRetencionesPagos_IB.pas' {FormListadoRetencionesOPago_IB},
  UListadoTCRecibidas in 'UListadoTCRecibidas.pas' {FormListadoMovTarjetasCreditoRecibidas},
  UListadoPercIB_FcVta in 'UListadoPercIB_FcVta.pas' {FormListadoPercIB_FcVta},
  UBuscadorRetGanancia in 'UBuscadorRetGanancia.pas' {FormBuscadoRetGanancia},
  UbuscadorRetIIBB in 'UbuscadorRetIIBB.pas' {FormBuscadorRetIIBB},
  UListadoTxStockPendientes in 'UListadoTxStockPendientes.pas' {FormListadoTxStockPendientes},
  UListadoFcCompraPorProveedor in 'UListadoFcCompraPorProveedor.pas' {FormListadoFcCompraPorProveedor},
  UBuscadorProveedor in 'UBuscadorProveedor.pas' {FormBuscadorProveedor},
  UAvisoCambioPrecio in 'UAvisoCambioPrecio.pas' {FormAvisoCambioPrecio},
  UAnulacionAdelantosSueldo in 'UAnulacionAdelantosSueldo.pas' {FormAnulacionAdelantos},
  UAnulacionDepositosBancarios in 'UAnulacionDepositosBancarios.pas' {FormAnulacionDepositoBancario},
  UListadoOperacionesClientes in 'UListadoOperacionesClientes.pas' {FormListadoOpercionesCliente},
  UControlIntegridadVentas in 'UControlIntegridadVentas.pas' {FormControlIntegridad},
  UEleccionCaja in 'UEleccionCaja.pas' {FormEleccionCaja},
  UControlSaldoCtaCteVta in 'UControlSaldoCtaCteVta.pas' {FormControlSaldoCtaCteVta},
  Utarjetacreditocompras in 'Utarjetacreditocompras.pas' {FormTarjetaCreditoCompra},
  UControlIntegridadCompra in 'UControlIntegridadCompra.pas' {FormControlIntegridadCompra},
  URemitoObra in 'URemitoObra.pas' {FormRemitoObra},
  DMRemitosObra in 'DMRemitosObra.pas' {DatosRemitosObra: TDataModule},
  UObras in 'UObras.pas' {FormObras},
  UBuscadorObras in 'UBuscadorObras.pas' {FormBuscadorObras},
  UPadronProveeEmbargo in 'UPadronProveeEmbargo.pas' {FormPadronEmbargos},
  UDetalleObras in 'UDetalleObras.pas' {FormDetallesObras},
  UListaPreciosProveedor in 'UListaPreciosProveedor.pas' {FormListaPreciosProvee},
  UChequesTercero in 'UChequesTercero.pas' {FormCheTercero},
  UImportarClientesExcel in 'UImportarClientesExcel.pas' {FormImportarClientesExcel},
  UConsultaArticuloProveedores in 'UConsultaArticuloProveedores.pas' {FormConsultaArticuloProveedores},
  UTasas_Ret_perc in 'UTasas_Ret_perc.pas' {FormTasasRet_Perc},
  UListaPreciosTabla in 'UListaPreciosTabla.pas' {FormListaPreciosTabla},
  UMuestraListaCodBarra in 'UMuestraListaCodBarra.pas' {FormMuestraListaCodigoBarra},
  UTasasPerc_Ret_IIBB in 'UTasasPerc_Ret_IIBB.pas' {FormTasaPercep_Ret},
  URMAEnvio in 'URMAEnvio.pas' {FormRMAEnvios},
  UImportarStockExcel in 'UImportarStockExcel.pas' {FormImportarStockExcel},
  UEtiquetas in 'UEtiquetas.pas' {FormEtiquetas},
  UBuscadorChequeras in 'UBuscadorChequeras.pas' {FormBuscadorChequeras},
  UListadoArtRMA in 'UListadoArtRMA.pas' {FormListadoRMA},
  URMARecepcion in 'URMARecepcion.pas' {FormRMARecepcion},
  URechazoRma in 'URechazoRma.pas' {FormRechazoRMA},
  UBuscadorTipoCpbte in 'UBuscadorTipoCpbte.pas' {FormBuscadorTipoCpbte},
  UTiketVta in 'UTiketVta.pas' {FormTicketVta},
  DMTicket in 'DMTicket.pas' {DatosVentasTicket: TDataModule},
  UNotaPedidoCliente in 'UNotaPedidoCliente.pas' {FormNotaPedidoCliente},
  DMNPedidoCliente in 'DMNPedidoCliente.pas' {DatosNPedidoClientes: TDataModule},
  UNPedidoClientePendientes in 'UNPedidoClientePendientes.pas' {FormNPedidoClientePendientes},
  UDistribuidores in 'UDistribuidores.pas' {FormDistribuidores},
  ULiquidacionTC in 'ULiquidacionTC.pas' {FormLiquidacionTC},
  UConciliacionChePropios in 'UConciliacionChePropios.pas' {FormConciliacionChePropios},
  UResumenTC in 'UResumenTC.pas' {FormResumentTC},
  UVtasRubro_Subrubro in 'UVtasRubro_Subrubro.pas' {FormVtaRubro_SubRubro},
  UImportarProveedoresExcel in 'UImportarProveedoresExcel.pas' {FormImportarProveedoresExcel},
  UListadoGastosTC in 'UListadoGastosTC.pas' {FormGastosTC},
  UFiltroCpbte_Vta in 'UFiltroCpbte_Vta.pas' {FormFiltroCpbte_vta},
  UActualizaCosto_Venta_excel in 'UActualizaCosto_Venta_excel.pas' {FormActulizaCostoVta_excel},
  UFiltroCpbte_Compra in 'UFiltroCpbte_Compra.pas' {FormFiltroCpbte_Compra},
  UIngAjustesExcel in 'UIngAjustesExcel.pas' {FormIngAjusCCExcel},
  URenombrarColumnaGrilla in 'URenombrarColumnaGrilla.pas' {FormRenombrarColumnaGrilla},
  UListadoRelacionCompraVenta in 'UListadoRelacionCompraVenta.pas' {FormListadoRelacionCompraVenta},
  UClonadoListaPrecio in 'UClonadoListaPrecio.pas' {FormClonadorListaPrecio},
  UListadoVtaArticulosClientesSuc in 'UListadoVtaArticulosClientesSuc.pas' {FormListadoVtaArticulosClienteSuc},
  UListadoCpbteGastosBco in 'UListadoCpbteGastosBco.pas' {FormListadoCpbteGastoBco},
  UHistorico_PrecioSombraPorArticulo in 'UHistorico_PrecioSombraPorArticulo.pas' {FormHistorico_PrecSombra_Art},
  UABPrecioSombra in 'UABPrecioSombra.pas' {FormABPrecioSombra},
  UCambioPrecio_sombra in 'UCambioPrecio_sombra.pas' {FormCambioPrecioSombra},
  UAsignaVendedorRC in 'UAsignaVendedorRC.pas' {FormAsignacionCobradorRC},
  UListadoRecibosPorVendedor in 'UListadoRecibosPorVendedor.pas' {FormListadoRecibosPorCobrador},
  UUltimasVtasMensual in 'UUltimasVtasMensual.pas' {FormUltimaVtaMensual},
  UCodigoProveedor_stock in 'UCodigoProveedor_stock.pas' {FormCodigoDeProveedores_Stock},
  UBuscadorDepositos in 'UBuscadorDepositos.pas' {FormBuscadorDepositos},
  UPedidosCumplidos in 'UPedidosCumplidos.pas' {FormPedidosCumplidos},
  UFlujoFondos in 'UFlujoFondos.pas' {FormFlujoFondos},
  UListadoClientesCondVta in 'UListadoClientesCondVta.pas' {FormListadoClienteConVenta},
  UListadoFacVencidas in 'UListadoFacVencidas.pas' {FormListadoFacVencidas},
  UListadovtaPorVendedor in 'UListadovtaPorVendedor.pas' {FormlistadoVtaPorVendedor},
  UBuscadorSubRubrosStock in 'UBuscadorSubRubrosStock.pas' {FormBuscadorSubRubroStock},
  UComposicionCobranza in 'UComposicionCobranza.pas' {FormComposicionCobranza},
  UBuscadorClientesAgenda in 'UBuscadorClientesAgenda.pas' {FormBuscadorClientesAgenda},
  USaldoClientesMensualAFecha in 'USaldoClientesMensualAFecha.pas' {FormSaldoClientesAlDia},
  UABCClientes in 'UABCClientes.pas' {FormABCClientes},
  UAlias in 'UAlias.pas' {FormAlias},
  UListCpbteNoImportados in 'UListCpbteNoImportados.pas' {FormListaNoImportados},
  UListadoCpbteVtaPorTipo in 'UListadoCpbteVtaPorTipo.pas' {FormListadoCpbteVtaPorTipo},
  UCodigoBarra in 'UCodigoBarra.pas' {FormCodigosBarra},
  UPresentaciones in 'UPresentaciones.pas' {Formpresentaciones},
  UDetalleOperacionesProvee in 'UDetalleOperacionesProvee.pas' {FormDetalleOperacionesProvee},
  UChe3DeppositadosAntes in 'UChe3DeppositadosAntes.pas' {FormChe3DepositadoAntes},
  UDetalleCompraArticulo in 'UDetalleCompraArticulo.pas' {formDetalleCompraArticulo},
  URegimenRetencionIVA in 'URegimenRetencionIVA.pas' {FormRegimenRetencionIVA},
  URemitosPendientesFacturacion in 'URemitosPendientesFacturacion.pas' {FormRtoPendientes},
  UPersonalAcciones in 'UPersonalAcciones.pas' {FormPersonalAcciones},
  UListadoConsumosTC in 'UListadoConsumosTC.pas' {FormListadoConsumosTC},
  UTransf_Interbnacarias in 'UTransf_Interbnacarias.pas' {FormTransferenciasInterbancarias},
  URemplazoValoresIngresados in 'URemplazoValoresIngresados.pas' {FormReemplazoValoresIng},
  UAsignarLote in 'UAsignarLote.pas' {FormAsignacionLoteTC},
  UPasaACC in 'UPasaACC.pas' {FormTransformaFactura},
  UCambiaNumeroCpbte in 'UCambiaNumeroCpbte.pas' {FormCambiaNroCpbte},
  UPlantillas in 'UPlantillas.pas' {FormPlantillas},
  UAbonosGrupos in 'UAbonosGrupos.pas' {FormAbonosGrupos},
  UListadoAjuestesStock in 'UListadoAjuestesStock.pas' {FormListadoAjustesStock},
  UAbonosGrilla in 'UAbonosGrilla.pas' {FormAbonosGrilla},
  UGeneradorCupones in 'UGeneradorCupones.pas' {FormGeneradorCupones},
  UDescuentosUsuarios in 'UDescuentosUsuarios.pas' {FormDescuentosUsuarios},
  UListaPreciosUsuario in 'UListaPreciosUsuario.pas' {FormListaPrecioUsuarios},
  UReciboAbonos in 'UReciboAbonos.pas' {FormReciboAbonos},
  UAbonosCupon in 'UAbonosCupon.pas' {FormAbonosCupon},
  UAdminstracionTareas in 'UAdminstracionTareas.pas' {FormAdminTareas},
  UPresupuestoOC in 'UPresupuestoOC.pas' {FormPresupuestoOC},
  UDescto_Presupuesto_oc in 'UDescto_Presupuesto_oc.pas' {FormDescuentosPresupOC},
  URecargos_Presupuesto_oc in 'URecargos_Presupuesto_oc.pas' {FormRecargosPresupOC},
  UBuscadorArticulosProveedor in 'UBuscadorArticulosProveedor.pas' {FormBuscadorArtiProv},
  UFecha in 'UFecha.pas' {FormFecha},
  UBuscaCupones in 'UBuscaCupones.pas' {FormBuscadorCupones},
  UCambiaClienteFecha_Recibo in 'UCambiaClienteFecha_Recibo.pas' {FormCambioClienteFecha_RC},
  UListadoVtasVsCobros in 'UListadoVtasVsCobros.pas' {FormVentasVsCobranza},
  UControlRetenciones in 'UControlRetenciones.pas' {FormControlRetenciones},
  UControlCuponTC in 'UControlCuponTC.pas' {FormControlCuponTC},
  UTxCajaPendientes in 'UTxCajaPendientes.pas' {FormTxPendientes},
  UDetallesNc_Rec in 'UDetallesNc_Rec.pas' {FormdetallesNc_Rec},
  UListaBuscadorOrdenCompra in 'UListaBuscadorOrdenCompra.pas' {FormListaOrdenCompra},
  UMuestraCpbteCtaCteVta in 'UMuestraCpbteCtaCteVta.pas' {FormMuestraCpbteCtaCteVta},
  UImportarMarcasExcel in 'UImportarMarcasExcel.pas' {FormImportarMarcasExcel},
  UCambioClienteFactura in 'UCambioClienteFactura.pas' {FormCambiaClienteFactura},
  UListadoCpbteCompPorTipo in 'UListadoCpbteCompPorTipo.pas' {FormListadoCpbteCompPorTipo},
  UCategoriaCliente in 'UCategoriaCliente.pas' {FormCategoriasClientes},
  UClientesIncidencias in 'UClientesIncidencias.pas' {FormClientesIncidencias},
  UNotaVenta in 'UNotaVenta.pas' {FormNotaVta},
  UDepositosUsuarios in 'UDepositosUsuarios.pas' {FormDepositosUsuarios},
  UListadoConsumosObras in 'UListadoConsumosObras.pas' {FormListadoConsumosObras},
  UABMLineaNotaVta in 'UABMLineaNotaVta.pas' {FormABMLineaNotavta},
  UNotasVersion in 'UNotasVersion.pas' {FormNotas},
  UUsuariosAutorizanPrecios in 'UUsuariosAutorizanPrecios.pas' {FormUsuariosAutorizan},
  UListadoTxCaja in 'UListadoTxCaja.pas' {FormListadoTxCaja},
  UListadoNVPendientes in 'UListadoNVPendientes.pas' {FormListadoNVPendientes},
  UListadoAcreditacionesTC in 'UListadoAcreditacionesTC.pas' {FormListadoAcreditacionesTC},
  UBuscadorNotaVenta in 'UBuscadorNotaVenta.pas' {FormBuscadorNotaVenta},
  UControlNroRto in 'UControlNroRto.pas' {FormControlNroRto},
  UListadoRtosAFiscal in 'UListadoRtosAFiscal.pas' {FormRtosAFiscal},
  UListadoStock in 'UListadoStock.pas' {FormListadoStock},
  UReArmaResumenBco in 'UReArmaResumenBco.pas' {FormReArmaResumenBco},
  UControlErroresMov in 'UControlErroresMov.pas' {FormControlErroresMovimientos},
  UPlantillas_Grillas in 'UPlantillas_Grillas.pas' {FormPlantillas_Grillas},
  UIngresoURL in 'UIngresoURL.pas' {FormURL},
  UListadoStockGeneral in 'UListadoStockGeneral.pas' {FormListadoStockGral},
  UNotaTransfStock in 'UNotaTransfStock.pas' {FormNota_TransfStock},
  UListadoNotaPedido in 'UListadoNotaPedido.pas' {FormListadoNotaPedido},
  DMNotasTransf in 'DMNotasTransf.pas' {DatosNotaTransferencia: TDataModule},
  UBuscadorNotaTransf in 'UBuscadorNotaTransf.pas' {FormBuscadorNotaTransferencia},
  UCambioCodigoCliente in 'UCambioCodigoCliente.pas' {FormCambioCodigoCliente},
  USaldoClientes_x_Cliente in 'USaldoClientes_x_Cliente.pas' {FormsaldoClientes_x_Cliente},
  UGeoPosicionClientes in 'UGeoPosicionClientes.pas' {FormPosicionGeoClientes},
  UGoogleMap in 'UGoogleMap.pas' {FormGoogleMap},
  UMuestraUltimoNroCpbte in 'UMuestraUltimoNroCpbte.pas' {FormMuestraUltimoProximoNroCpbte},
  UVtaPorVendedorDiaria in 'UVtaPorVendedorDiaria.pas' {FormVtaVendedorDiaria},
  UAvisoCambioPrecioCompra in 'UAvisoCambioPrecioCompra.pas' {FormAvisoCambioPrecioCompra},
  UIngresoCotizacion in 'UIngresoCotizacion.pas' {FormCotizacion},
  UControlChe3 in 'UControlChe3.pas' {FormControlChe3},
  UMuestraSaldoCliente in 'UMuestraSaldoCliente.pas' {FormSaldoUnCLiente},
  UChequesEmitidosDetalle in 'UChequesEmitidosDetalle.pas' {FormChequesEmitidosDetalle},
  UUsuariosAdminNP in 'UUsuariosAdminNP.pas' {FormUsuariosAdminNP},
  UGrupoDetalleFacturacion in 'UGrupoDetalleFacturacion.pas' {FormGrupoDetalleFactura},
  UAsignaGrupoDetalleVta in 'UAsignaGrupoDetalleVta.pas' {FormAgrupamientoDetalle},
  UProveedor_x_CtaOrden in 'UProveedor_x_CtaOrden.pas' {FormProveedor_x_CtaOrden},
  UCambiaClaseComprobante in 'UCambiaClaseComprobante.pas' {FormCambiarClaseCpbte},
  DMMainForm_2 in 'DMMainForm_2.pas' {DMMain_2: TDataModule},
  DMBuscadoresForm in 'DMBuscadoresForm.pas' {DMBuscadores: TDataModule},
  DMStoreProcedureForm in 'DMStoreProcedureForm.pas' {DMStoreProcedure: TDataModule},
  UPlanillaArmado in 'UPlanillaArmado.pas' {FormPlanillaArmado},
  DMArmadoProductos in 'DMArmadoProductos.pas' {DatosArmadoProductos: TDataModule},
  UBuscadorPlanillaProduccion in 'UBuscadorPlanillaProduccion.pas' {FormBuscadorPlanillaArmadoProduccion},
  UCambiaProv_Fecha_OPago in 'UCambiaProv_Fecha_OPago.pas' {FormCambiaProvFecha_OPago},
  UFacturarPlantillas in 'UFacturarPlantillas.pas' {FormFacturaPlantillas},
  UConfiguracionRecibo in 'UConfiguracionRecibo.pas' {FormConfiguracionRecibo},
  DMNotaVenta in 'DMNotaVenta.pas' {DatosNotaVenta: TDataModule},
  DMPresupuestoOC in 'DMPresupuestoOC.pas' {DatosPresupuestoOC: TDataModule},
  USumaAplicaciones in 'USumaAplicaciones.pas' {FormSumaAplicaciones},
  UMuestraCpbteCtaCteCompra in 'UMuestraCpbteCtaCteCompra.pas' {FormMuestraCpbteCtaCteCompra},
  DMCaja in 'DMCaja.pas' {DatosCaja: TDataModule},
  UConfiguracionOrdenPago in 'UConfiguracionOrdenPago.pas' {FormConfiguracionOPago},
  UMontoATransferir in 'UMontoATransferir.pas' {FormMontoATransferir},
  URecepcionGarantias in 'URecepcionGarantias.pas' {FormRecepGarantia},
  DMLiquidacionTC in 'DMLiquidacionTC.pas' {DatosLiquidacionTC: TDataModule},
  UControlItemCompra in 'UControlItemCompra.pas' {FormControlDetalleComp},
  UListadoStockConsignacion in 'UListadoStockConsignacion.pas' {FormStockConsignacion},
  DMGastosBancarios in 'DMGastosBancarios.pas' {DatosGastosBco: TDataModule},
  UListadoRecepGtias in 'UListadoRecepGtias.pas' {FormListadoRecepGtias},
  UJuridicion_Localidad in 'UJuridicion_Localidad.pas' {FormJuridicion_Localidad},
  UConsultaPrecio in 'UConsultaPrecio.pas' {FormConsultaPrecio},
  UGtias_Ext in 'UGtias_Ext.pas' {FormGtias_Ext},
  UListadoRecibosPorVendedor_2 in 'UListadoRecibosPorVendedor_2.pas' {FormListadoRecibosPorCobrador_2},
  UControlMesesGtia in 'UControlMesesGtia.pas' {FormControlGtia},
  UAsignacionJuridiccion in 'UAsignacionJuridiccion.pas' {FormAsignacionJuridiccion},
  UCambiaDespositoFc in 'UCambiaDespositoFc.pas' {FormCambioDeposito},
  UJuridiccionExcepcion in 'UJuridiccionExcepcion.pas' {FormJuridicion_Sucursal},
  UListadoClientesUltimaVta in 'UListadoClientesUltimaVta.pas' {FormListadoUltimaVtaCliente},
  UCantidadEtiquetas in 'UCantidadEtiquetas.pas' {FormCantidadEtiquetas},
  UBuscadorBaseDatos in 'UBuscadorBaseDatos.pas' {FormBuscadorBaseDatos},
  UImagen in 'UImagen.pas' {FormImagen},
  UDepositoTxMercaderia in 'UDepositoTxMercaderia.pas' {FormMuestraDepositoTransferencia},
  USumaAplicacionesRc in 'USumaAplicacionesRc.pas' {FormSumaAplicacionesRc},
  UPanelControlOP in 'UPanelControlOP.pas' {FormControlOP},
  UListadoChePorOrdenPago in 'UListadoChePorOrdenPago.pas' {FormListadoChePor_OPago},
  UNumeroOperacion in 'UNumeroOperacion.pas' {FormNumeroOperacion},
  UServicioTecnico in 'UServicioTecnico.pas' {FormServicioTecnico},
  UArticulosSTExterno in 'UArticulosSTExterno.pas' {FormArticulos_STExterno},
  UAcopio in 'UAcopio.pas' {FormAcopio},
  UBuscadorAcopios in 'UBuscadorAcopios.pas' {FormBuscadorAcopios},
  URtoEntregaAcopio in 'URtoEntregaAcopio.pas' {FormRtoEntregaAcopio},
  UListadoCompraArticulosProveedor in 'UListadoCompraArticulosProveedor.pas' {FormLisCompraArt_Proveedor},
  ULstComparativoArtPorCompra in 'ULstComparativoArtPorCompra.pas' {FormComparaArtPorCompra},
  UTransferenciasStockAnulada in 'UTransferenciasStockAnulada.pas' {FormTransfStockAnuladas},
  UCambioProveedorFactura in 'UCambioProveedorFactura.pas' {FormCambiaProveedorFactura},
  UCambioCodigoStock in 'UCambioCodigoStock.pas' {FormCambioCodigoStock},
  UListarFacturasFrezadas in 'UListarFacturasFrezadas.pas' {FormListadoFacturasClonadas},
  URelacionCobranzaVencimiento in 'URelacionCobranzaVencimiento.pas' {FormRelacionCobranzaVencimiento},
  UIngresaNroOP in 'UIngresaNroOP.pas' {FormIngresaNroOP},
  UIngresoCantNV in 'UIngresoCantNV.pas' {FormIngresoCantidad},
  UValorCuotaTC in 'UValorCuotaTC.pas' {FormValorCuotaTC},
  UIngresoCantNT in 'UIngresoCantNT.pas' {FormIngresoCantidadNT},
  ULista_Stock_rub_subrub in 'ULista_Stock_rub_subrub.pas' {FormLista_Stock_Rub_SubRub},
  UBuscadorCtaContables in 'UBuscadorCtaContables.pas' {FormBuscadorCtaContable},
  DMContableForm in 'DMContableForm.pas' {DMContable: TDataModule},
  UCtaContables in 'UCtaContables.pas' {FrameCtaContable: TFrame},
  UListadoGastoRefContable in 'UListadoGastoRefContable.pas' {FormListadoGastoRefContable},
  UConfiguraPath in 'UConfiguraPath.pas' {FormConfiguraPath},
  UClaveVerificada in 'UClaveVerificada.pas' {FormClaveVerificada},
  UAdministraEstadoStock in 'UAdministraEstadoStock.pas' {FormAdminEstadosStock},
  UImportarPorcentajes in 'UImportarPorcentajes.pas' {FormImportarPorcentajes},
  UNumeroInterno in 'UNumeroInterno.pas' {FormNumeroInterno},
  UImportarRubroExcel in 'UImportarRubroExcel.pas' {FormImportarRubroExcel},
  UImportarSubRubroExcel in 'UImportarSubRubroExcel.pas' {FormImportarSubRubroExcel},
  UIngresoLotePersonal in 'UIngresoLotePersonal.pas' {FormRetiroLotesPersonal},
  UPanelVtas_Compras in 'UPanelVtas_Compras.pas' {FormPanelVtas_Compras},
  UCambioCajaMov in 'UCambioCajaMov.pas' {FormCambioCajaMov},
  UBuscadorReciboNroInt in 'UBuscadorReciboNroInt.pas' {FormBuscadorReciboNroInt},
  UImportarVtas_PtoVta in 'UImportarVtas_PtoVta.pas' {FormImportarVtas_PtoVtaMorphi},
  USeleccionCajaNC in 'USeleccionCajaNC.pas' {FormSeleccionCajaNC},
  UReemplazoSubRubro in 'UReemplazoSubRubro.pas' {FormRemplazoSubRubro},
  UMuestraArtPorSubRub in 'UMuestraArtPorSubRub.pas' {FormMuestraArtPorSubRubros},
  UCambioListaClientes in 'UCambioListaClientes.pas' {FormCambioListaCliente},
  UBuscadorMarcas in 'UBuscadorMarcas.pas' {FormBuscadorMarca},
  UVencimientos in 'UVencimientos.pas' {FormVencimientos},
  UABMVencimientos in 'UABMVencimientos.pas' {FormABMVencimientos},
  UFiltroComprobantesVenta in 'UFiltroComprobantesVenta.pas' {FormFiltroCpbtes},
  UABCCompraArticulos in 'UABCCompraArticulos.pas' {FormABCCompraArticulos},
  UControlCpbteRecibidos in 'UControlCpbteRecibidos.pas' {FormCpbteRecibidos},
  UImpresionCUponesAbonos in 'UImpresionCUponesAbonos.pas' {FormImpresionCuponesAbonos},
  UResumenVentas in 'UResumenVentas.pas' {FormResumenVentas},
  UGrafico in 'UGrafico.pas' {FormGrafico},
  UResumenVtasRubros_Subr_anual in 'UResumenVtasRubros_Subr_anual.pas' {FormResumenVtaRubro_Sub_Anual},
  UResumenVtasAnualVendedor in 'UResumenVtasAnualVendedor.pas' {FormResumenAnualVtasVendedor},
  UPrecioEspecialCliente in 'UPrecioEspecialCliente.pas' {FormLstPreciosEspecialesClientes},
  UPagosPersonalAnual in 'UPagosPersonalAnual.pas' {FormPagosPersonalAnual},
  UCambioArticuloVta in 'UCambioArticuloVta.pas' {FormCambiaArticuloEnVtas},
  UCambioVendedor in 'UCambioVendedor.pas' {FormCambioVendedor},
  UCheCompartidos in 'UCheCompartidos.pas' {FormCheCompartidos},
  UControlRtosVsPedido in 'UControlRtosVsPedido.pas' {FormControlRtosVsPedido},
  UBuscadorCheCompartido in 'UBuscadorCheCompartido.pas' {FormBuscadoCheCompartido},
  UListadoChRecibidos in 'UListadoChRecibidos.pas' {FormListadoChRecibidos},
  UNotasCambio in 'UNotasCambio.pas' {FormNotas_Cambio},
  DMNotasCambio in 'DMNotasCambio.pas' {DatosNotasCambio: TDataModule},
  UModoVenta in 'UModoVenta.pas' {FormModoVta},
  UConfiguracionNotaCambio in 'UConfiguracionNotaCambio.pas' {FormConfiguracionNotaCambio},
  UBuscadorCambiosArticulos in 'UBuscadorCambiosArticulos.pas' {FormBuscadorCambios},
  UClienteCotizacion in 'UClienteCotizacion.pas' {FormClienteCotizacion},
  UMovTemporalStock in 'UMovTemporalStock.pas' {FormMovTemporalesStock},
  UControlMovCtaCteVta_detalle in 'UControlMovCtaCteVta_detalle.pas' {FormControlMovCtaVta_Detalles},
  UReferenciasPreciosClientes in 'UReferenciasPreciosClientes.pas' {FormReferencias},
  UAsignacionesEmpleados in 'UAsignacionesEmpleados.pas' {FormAsignacionesPersonal},
  UListadoCpbteVta in 'UListadoCpbteVta.pas' {FormListadoCpbteVta},
  UListadoCpbteCompra in 'UListadoCpbteCompra.pas' {FormListCpbteCompra},
  UStock_descuentos in 'UStock_descuentos.pas' {FormStock_Dstos},
  UListaPorSucursal in 'UListaPorSucursal.pas' {FormListaSucursal},
  UComposicionIvaVta in 'UComposicionIvaVta.pas' {FormComposicionIvaVta},
  UBuscadorReciboCupon in 'UBuscadorReciboCupon.pas' {FormBuscadorPagoCupones},
  UControlVtoCupones in 'UControlVtoCupones.pas' {FormControlVtoCupones},
  UIngresosCtaEmpleadoLote in 'UIngresosCtaEmpleadoLote.pas' {FormIngresoPorLotePersonal},
  UComprobContabilizar in 'UComprobContabilizar.pas' {FormCpbteContabilizar},
  UGraficoEgresos in 'UGraficoEgresos.pas' {FormGraficoEgresos},
  UConceptosPlantillas in 'UConceptosPlantillas.pas' {FormConceptosPlantillas},
  UListadoOperaciones in 'UListadoOperaciones.pas' {FormListaPorOperaciones},
  UControlItemVta in 'UControlItemVta.pas' {FormControlDetalleVta},
  UPanelImportacionVtas in 'UPanelImportacionVtas.pas' {FormPanelImportacionVta},
  UCambiaFechaNroChe in 'UCambiaFechaNroChe.pas' {FormModificarDatosChPropio},
  USeleccionLista in 'USeleccionLista.pas' {FormSeleccionLista},
  DMImportacion in 'DMImportacion.pas' {DatosImportacion: TDataModule},
  DMImportacion_Input in 'DMImportacion_Input.pas' {DatosImportacionInput: TDataModule},
  UPanelImportacionComp in 'UPanelImportacionComp.pas' {FormPanelImportacionComp},
  DMImportacionComp in 'DMImportacionComp.pas' {DatosImportacioComp: TDataModule},
  DMImportacionComp_Input in 'DMImportacionComp_Input.pas' {DatosImportacionComp_Input: TDataModule},
  UImportarCobroCupones in 'UImportarCobroCupones.pas' {FormImportarCobroCupones},
  UListadoChe3PorCpbteIng in 'UListadoChe3PorCpbteIng.pas' {FormListadoChe3PorCpbte},
  UMuestraEstadoCta in 'UMuestraEstadoCta.pas' {formEstadoCta},
  UArtFacRtos in 'UArtFacRtos.pas' {FormActFacturacionRtos},
  UCtroCosto in 'UCtroCosto.pas' {FormCtroCosto},
  UAsignacionCtroCosto in 'UAsignacionCtroCosto.pas' {FormAsignacionCentroCosto},
  UListadoPorCtrosCosto in 'UListadoPorCtrosCosto.pas' {FormLstPorCtroCosto},
  UInformeGeneral in 'UInformeGeneral.pas' {FormInformeGeneral},
  UArticulosFacCompra in 'UArticulosFacCompra.pas' {FormReempArticuloFcCompra},
  UFiltroRubGastos in 'UFiltroRubGastos.pas' {FormFiltroRubGastos},
  UCajaResumen in 'UCajaResumen.pas' {FormCajaResumen},
  UControlCuponAbono in 'UControlCuponAbono.pas' {FormControlCuponAbono},
  UCambiaFecha_Cta_LiqTC in 'UCambiaFecha_Cta_LiqTC.pas' {FormCambioFechaLiqTC},
  UCambiaFecha_GastoBco in 'UCambiaFecha_GastoBco.pas' {FormCambioFechaGastoBco},
  UBuscadorRetenciones in 'UBuscadorRetenciones.pas' {FormBuscadorRetenciones},
  UCambioFechaFiscal in 'UCambioFechaFiscal.pas' {FormFechaFiscal},
  UListadoMovStock_Diario in 'UListadoMovStock_Diario.pas' {FormListadoMovStockDiario},
  UBuscadorGastoBancario in 'UBuscadorGastoBancario.pas' {FormBuscadorGastosBancarios},
  UBuscarPorNroReferencia in 'UBuscarPorNroReferencia.pas' {FormBuscarPorNroReferenica},
  UConsolidacionDeudaClientes in 'UConsolidacionDeudaClientes.pas' {FormConsolidacionDeudaCliente},
  UOPagoExcluidasGanacia in 'UOPagoExcluidasGanacia.pas' {FormOPagoExcluidasGanancia},
  UListadoSeries in 'UListadoSeries.pas' {FormListadoSeries},
  UBuscadorHojaCarga in 'UBuscadorHojaCarga.pas' {FormBuscadorHojaCarga},
  UGastosIngresosConsolidados in 'UGastosIngresosConsolidados.pas' {FormGastosIngresosConsolidados},
  UCopiaPrecios in 'UCopiaPrecios.pas' {FormCopiaPrecios},
  UTipoServicio in 'UTipoServicio.pas' {FormTipoServicio},
  ULstStock_Precio_Fisico in 'ULstStock_Precio_Fisico.pas' {FormLstStock_Precio_Fisico},
  UComposicionVta_Cobros in 'UComposicionVta_Cobros.pas' {FormComposicionVtas_Cobros},
  UNovedadesStock in 'UNovedadesStock.pas' {FormNovedadesStock},
  UAsignacionCtaGastoStock in 'UAsignacionCtaGastoStock.pas' {FormAsignacionCtaGastoStock},
  UDetalleCarnes in 'UDetalleCarnes.pas' {FormMovimientosCarnes},
  UControlsStockRubros in 'UControlsStockRubros.pas' {FormControlStockRubros},
  UListadoPagosPersonal in 'UListadoPagosPersonal.pas' {FormListadoPagoPersonal},
  UControlMovChe3 in 'UControlMovChe3.pas' {FormControlMovChe3},
  UCambioVendedor_clientes in 'UCambioVendedor_clientes.pas' {FormClientes_Vendedor},
  UMovSalidaChe3 in 'UMovSalidaChe3.pas' {FormMovSalidaChe3},
  UControlRetIIBTarjeta in 'UControlRetIIBTarjeta.pas' {FormControlIIBBLiq},
  UTablaChequesTercero in 'UTablaChequesTercero.pas' {FormTablaCheques3},
  UControl_Rto_Fc in 'UControl_Rto_Fc.pas' {FormControlAsignacionRto_Fc},
  UMuestraIngresosPersonal in 'UMuestraIngresosPersonal.pas' {FormMuestraIngresosPersonal},
  UImprimirLoteVales in 'UImprimirLoteVales.pas' {FormImpresionLoteVales},
  UExistenciasConMov in 'UExistenciasConMov.pas' {FormExistenciaConMov},
  UMovStockDiario in 'UMovStockDiario.pas' {FormMovStockDiario},
  UURelacionPagoVencimientoProveed in 'UURelacionPagoVencimientoProveed.pas' {FormRelacionPagosProveedores},
  URevisionMovChe3 in 'URevisionMovChe3.pas' {FormRevisionMovChe3},
  USaldoProveedorAFecha in 'USaldoProveedorAFecha.pas' {FormSaldoProveedorAlDia},
  UReImportacionAplicacionesCompra in 'UReImportacionAplicacionesCompra.pas' {FormReImpAplicacionesCompra},
  UBuscadorLiqTC in 'UBuscadorLiqTC.pas' {FormBuscadorLiquidacionTC},
  UReImportacionAplicacionesVta in 'UReImportacionAplicacionesVta.pas' {FormReImpAplicacionesVta},
  UCompIngresosEgresos in 'UCompIngresosEgresos.pas' {FormComposicionIngEgre},
  UComposicionVtos_Compra in 'UComposicionVtos_Compra.pas' {FormComposicionVtosComp},
  UFiscalizacion in 'UFiscalizacion.pas' {FormFiscalizacion},
  UClonarCpbtes in 'UClonarCpbtes.pas' {FormClonarCpbtes},
  UComposicionVtos_Vtas in 'UComposicionVtos_Vtas.pas' {FormComposicionDeudaVta},
  UControlRtosHuerfanos in 'UControlRtosHuerfanos.pas' {FormControlRtosHuerfanos},
  UCalculadorFinaciero in 'UCalculadorFinaciero.pas' {FormCalculadorFinanciero},
  URecepcionTxStock in 'URecepcionTxStock.pas' {FormRecepcionTxStock},
  UFiscalizarLote in 'UFiscalizarLote.pas' {FormFiscalizacionLote},
  UValoresImportacionVtas in 'UValoresImportacionVtas.pas' {FormValoresIngresarImporVtas},
  UImportarAjustes in 'UImportarAjustes.pas' {FormPanelImportacionAjustesStock},
  UImportarAjustesStk in 'UImportarAjustesStk.pas' {FormImportacionAjustesStk},
  UImportacionEstadoStock in 'UImportacionEstadoStock.pas' {FormImportacionExistencias},
  UVtas_Fondos in 'UVtas_Fondos.pas' {FormComposicionIngresos},
  UControlFactModelo in 'UControlFactModelo.pas' {FormControlFcModelo},
  UFacturaProduccion in 'UFacturaProduccion.pas' {FormCpbte_Produccion},
  UListadoArtiPendientesOC in 'UListadoArtiPendientesOC.pas' {FormArtPendientesOC},
  UBuscadorComprobantes in 'UBuscadorComprobantes.pas' {FormBuscaComprobantes},
  UNroCuit_Doc in 'UNroCuit_Doc.pas' {FormCuit_Doc},
  UBuscadorPorObs in 'UBuscadorPorObs.pas' {FormBuscadorPorObs},
  UFormResolcucion3668 in 'UFormResolcucion3668.pas' {FormResolucion3668},
  UImportacionPreventa in 'UImportacionPreventa.pas' {FormImportacionPreventas},
  UPizarronOT in 'UPizarronOT.pas' {FormPizarronOT},
  UPizarronAcopios in 'UPizarronAcopios.pas' {FormPizarronAcopios},
  UFrameAcopios in 'UFrameAcopios.pas' {FrameAcopios: TFrame},
  ULstMercaderiaAcopio in 'ULstMercaderiaAcopio.pas' {FormLstMercaderiaAcopio},
  UPlanillaPedido in 'UPlanillaPedido.pas' {FormPlanillaPedido},
  ULoteSeriales in 'ULoteSeriales.pas' {FormLoteSeriales},
  UBuscadorAcopiosActivos in 'UBuscadorAcopiosActivos.pas' {FormBuscadorAcopiosActivos},
  UControlGrillaVta in 'UControlGrillaVta.pas' {FormControlDetalle},
  UCantidadCuotas in 'UCantidadCuotas.pas' {FormCantidadCuotas},
  UFiltroRubros in 'UFiltroRubros.pas' {FormFiltroRubros},
  UPedidoPorCliente in 'UPedidoPorCliente.pas' {FormPedidoPorCliente},
  UEntregasAcopios in 'UEntregasAcopios.pas' {FormListadoEntregasAcopios},
  UGeneradorDebitosTC in 'UGeneradorDebitosTC.pas' {FormClientesDebTC},
  UBorradorPedido in 'UBorradorPedido.pas' {FormBorradorPedido},
  UTiketPago in 'UTiketPago.pas' {FormABMBase2},
  UPrestadores in 'UPrestadores.pas' {FormPrestadores},
  DMRtosMk in 'DMRtosMk.pas' {DatosRtoMk: TDataModule},
  UDetalleEntregasAcopio in 'UDetalleEntregasAcopio.pas' {FormMuestraEntregasAcopios},
  UComprobantesAfip in 'UComprobantesAfip.pas' {FormCodComprobantesAfip},
  URubrosFueraPromo in 'URubrosFueraPromo.pas' {FormRubrosFueraPromocion},
  UNovedadesFacturacion in 'UNovedadesFacturacion.pas' {FormNovedadesFacturacion},
  UPanelComisionObjetivos in 'UPanelComisionObjetivos.pas' {FormComisionVtaObjetivo},
  UImportacionFacCompra in 'UImportacionFacCompra.pas' {FormImportacionCompraGral},
  UClientes_Adicionales in 'UClientes_Adicionales.pas' {FormClientesAdicionales},
  UDetalleRegConsolidacion in 'UDetalleRegConsolidacion.pas' {FormRegConsolidacion},
  UProyeccionAnuales in 'UProyeccionAnuales.pas' {FormProyeccionAnuales},
  UImportacionFacVta in 'UImportacionFacVta.pas' {FormImportacionFacturasVtaGral},
  UCambiarNro in 'UCambiarNro.pas' {FormCambiarNro},
  UCantidadPedir in 'UCantidadPedir.pas' {FormCantidadPedir},
  URegLiquiComisiones in 'URegLiquiComisiones.pas' {FormRegLiquidacionComi},
  UAdministraGarantes in 'UAdministraGarantes.pas' {FormAdministracionGarantes},
  ULstPlantillas in 'ULstPlantillas.pas' {FormLstPlantillas},
  UFeriados in 'UFeriados.pas' {FormFeriados},
  UMuestraGarantes in 'UMuestraGarantes.pas' {FormGarantes},
  UPreciosCompra in 'UPreciosCompra.pas' {FormTrazabilidadPreciosCompra},
  UImportarDsctos in 'UImportarDsctos.pas' {FormImpDscto},
  UEntregas_VtaAnticipada in 'UEntregas_VtaAnticipada.pas' {FormEntregas_VtaAnticipadas},
  UResumenCaja in 'UResumenCaja.pas' {FormResumenCaja},
  UConsolidacionAcopioRtos in 'UConsolidacionAcopioRtos.pas' {FormConsolidacionAcopioRemitos},
  UVtas_Rec in 'UVtas_Rec.pas' {FormVta_Rec},
  UListadoOTrabajo in 'UListadoOTrabajo.pas' {FormListadoOT},
  UBuscadorCpbteNro in 'UBuscadorCpbteNro.pas' {FormBuscadorComprobNro},
  UAsignacionCtroCostoFVta in 'UAsignacionCtroCostoFVta.pas' {FormAsignaCtroCostoVta},
  UGeneradorCuotasVtos in 'UGeneradorCuotasVtos.pas' {FormCuotasVencimientos},
  UBuscadorVencimientos in 'UBuscadorVencimientos.pas' {FormBuscadorVencimientos},
  UDetalleMovCaja_Cpbte in 'UDetalleMovCaja_Cpbte.pas' {FormDetalleValores},
  UImportarCobroRipsa in 'UImportarCobroRipsa.pas' {FormCobrosRipsa},
  UVistasGrillas in 'UVistasGrillas.pas' {FormVistaGrillas},
  UCobroConTarjetaCredito in 'UCobroConTarjetaCredito.pas' {FormCobroConTarjetasCredito},
  Vcl.Themes,
  Vcl.Styles,
  UPedidosMorphi in 'UPedidosMorphi.pas' {FormPedidosMorphi},
  UBuscadorDespachos in 'UBuscadorDespachos.pas' {FormBuscadorDespachos},
  UDespachoImpo in 'UDespachoImpo.pas' {FormDespachoImpo},
  UOrdenTrabajoPendientes in 'UOrdenTrabajoPendientes.pas' {FormListadoOTrabajoPendientes},
  UConversorFcVta_a_Comp in 'UConversorFcVta_a_Comp.pas' {FormConversorFcVta_a_Compra},
  UControlTxBancarias in 'UControlTxBancarias.pas' {FormControlTxBancarias},
  UInformeVariablesVtas_Stock in 'UInformeVariablesVtas_Stock.pas' {FormVtas_UnicoStock},
  UCobranzaPorLote in 'UCobranzaPorLote.pas' {FormCobranza_x_lote},
  UBuscadorXidentificador in 'UBuscadorXidentificador.pas' {FormBuscadorXidentific},
  uMainConsultaCuit in 'uMainConsultaCuit.pas' {FormConsultaCuit},
  UListadoRtosDetalle in 'UListadoRtosDetalle.pas' {FormListadoRtosDetalle},
  UMotivosOT in 'UMotivosOT.pas' {FormMotivosOTrabajo},
  UControlChePropio in 'UControlChePropio.pas' {FormControlChequesDuplicados},
  URubroClientes in 'URubroClientes.pas' {FormRubroClientes},
  UPlanerOTrabajo in 'UPlanerOTrabajo.pas' {FormPlanerOTrabajo},
  UAjustesLotes in 'UAjustesLotes.pas' {FormAjusteLotes},
  UCuentaCCAcopio in 'UCuentaCCAcopio.pas' {FormCTaCteAcopio},
  UCashFlow_LF in 'UCashFlow_LF.pas' {FormCahsFlow_LF},
  UNroSeries in 'UNroSeries.pas' {FormNroSeries},
  UAnexosRtoTransporte in 'UAnexosRtoTransporte.pas' {FormAnexosRtoTransporte},
  UAdminTransporte in 'UAdminTransporte.pas' {FormAdminTransporte},
  UVencimientosTransp in 'UVencimientosTransp.pas' {FormVtosTransportes},
  UUnidadesTR in 'UUnidadesTR.pas' {FormUnidadesTr},
  UUnidadesTR_Anexos in 'UUnidadesTR_Anexos.pas' {FormUnidadesAnexos},
  UPanificacionProduccion in 'UPanificacionProduccion.pas' {FormPlanificacion_Produccion},
  UOrdenDeTrabajo_Estaciones in 'UOrdenDeTrabajo_Estaciones.pas' {FormEstacionProduccion},
  ULeerArchivoTCVisa in 'ULeerArchivoTCVisa.pas' {FormLeerArchivoTCVisa},
  ULstMovCaja in 'ULstMovCaja.pas' {FormLstMovCajaGeneral},
  UBuscadorClientesAbonos in 'UBuscadorClientesAbonos.pas' {FormBuscadorClientesAbonados},
  ULstControlOTrabajo in 'ULstControlOTrabajo.pas' {FormControlOTrabajo},
  UBuscadorAjustesLotes in 'UBuscadorAjustesLotes.pas' {FormBuscadorAjustesLotes},
  UTipoAdicionalCompra in 'UTipoAdicionalCompra.pas' {FormAdicionalesCompra},
  UMovAuxCCComp in 'UMovAuxCCComp.pas' {FormMovAuxCCComp},
  UBuscadorTipoAdCompra in 'UBuscadorTipoAdCompra.pas' {FormBuscadorTipoMovCCComp},
  UBuscadorMovAuxCCComp in 'UBuscadorMovAuxCCComp.pas' {FormBuscadorMovAuxCCComp},
  UArticulosUsadosRtos in 'UArticulosUsadosRtos.pas' {FormArticulosUsadosRtos},
  UExportarExcelListaPrecios in 'UExportarExcelListaPrecios.pas' {FormExportarExcelLista},
  UFiltroMarcas in 'UFiltroMarcas.pas' {FormFiltrosMarcas},
  UDetalleMovProduccion in 'UDetalleMovProduccion.pas' {FormDetalleMovimientosProduccion},
  UOrdenProduccionSector in 'UOrdenProduccionSector.pas' {FormSectoresProduccion},
  UProduccion_PDiario in 'UProduccion_PDiario.pas' {FormProducc_Diario},
  UProduccion_Material in 'UProduccion_Material.pas' {FormProduccionMateriales},
  UControlDuplicadoProduccion in '..\Prueba LocalSQL\UControlDuplicadoProduccion.pas' {FormControlDuplicadoProduccion},
  USaldosClientesXLS in 'USaldosClientesXLS.pas' {FormSaldosClientesXLS},
  UChequesAnulados in 'UChequesAnulados.pas' {FormChequesAnulados},
  UEtiquetas_2 in 'UEtiquetas_2.pas' {FormEtiquetaOP},
  UPedidosResumen in 'UPedidosResumen.pas' {FormPedidosResumen},
  USaldosProveedoresXLS in 'USaldosProveedoresXLS.pas' {FormSaldoProveedoresXLS},
  UExportadorRtos in 'UExportadorRtos.pas' {FormExportaRe},
  UImportarRtos in 'UImportarRtos.pas' {FormImportarRtos},
  UPedidos in 'UPedidos.pas' {FormPedidos},
  UMuestraHRuta in 'UMuestraHRuta.pas' {FormMuestraHRuta},
  UMotivosVales in 'UMotivosVales.pas' {FormMotivosPersonal},
  UImportarEmpleadosExcel in 'UImportarEmpleadosExcel.pas' {FormImportarEmpleadosXLS},
  UPendientesOC in 'UPendientesOC.pas' {FormPendientesOC},
  UDetallePedidos in 'UDetallePedidos.pas' {FormDetallePedidosRealizados},
  UExportarLibroIvaComp_excel in 'UExportarLibroIvaComp_excel.pas' {FormExportarLibroIvaExcel},
  UListadoAjustesCtasCtes in 'UListadoAjustesCtasCtes.pas' {FormListadoAjustesCC},
  UMotivosAjustesCCVta in 'UMotivosAjustesCCVta.pas' {FormMotivosAjustesCCVta},
  UMotivosAjustesCCComp in 'UMotivosAjustesCCComp.pas' {FormMotivosAjustesCCComp},
  UImpresionChePropios in 'UImpresionChePropios.pas' {FormImpresionChePropios},
  UFactura_2 in 'UFactura_2.pas' {FormCpbte_2},
  UPrecios_x_Cantidades in 'UPrecios_x_Cantidades.pas' {FormPreciosPorCantidades},
  UPlantillasNoFacturadas in 'UPlantillasNoFacturadas.pas' {FormPlantillasNoFacturables},
  URtoTroqueles in 'URtoTroqueles.pas' {FormRtoTroqueles},
  UListadoPresuDetalle in 'UListadoPresuDetalle.pas' {FormLstPresupuestoDetalle},
  UHistorialCajas in 'UHistorialCajas.pas' {FormHistorialCajas},
  UMotivoAjusteStock in 'UMotivoAjusteStock.pas' {FormMotivoAjustesStock},
  URetencionIva_Efectuadas in 'URetencionIva_Efectuadas.pas' {FormRetIva_EfectuadasLiq},
  USucursalesExportacionIVA in 'USucursalesExportacionIVA.pas' {FormSucursalesExportacion},
  UMovTarjetaCredito in 'UMovTarjetaCredito.pas' {FormMovTarjetaCredito},
  UHistorialMovCaja in 'UHistorialMovCaja.pas' {FormHistorialMovCaja},
  UExportarLibroIvaVta_excel in 'UExportarLibroIvaVta_excel.pas' {FormExportarLibroIvaVtaExcel},
  URevisionValoresIngreso in 'URevisionValoresIngreso.pas' {FormRevisionValoresIngreso},
  URevisionValoresEgresados in 'URevisionValoresEgresados.pas' {FormRevisionValoresEgresados},
  DMLiborIvaVta in 'DMLiborIvaVta.pas' {DatosLibroIvaVta: TDataModule},
  DMLiborIvaCompra in 'DMLiborIvaCompra.pas' {DatosLibroIvaCompra: TDataModule},
  DMCtaCteVta in 'DMCtaCteVta.pas' {DatosCCVta: TDataModule},
  UImprimirHojaCargaAgrupada in 'UImprimirHojaCargaAgrupada.pas' {FormImpresionHojaCargaAgrupada},
  UReciboExpress in 'UReciboExpress.pas' {FormReciboExpress},
  DMResumenVtas in 'DMResumenVtas.pas' {DatosResumenVtas: TDataModule},
  ULstTransfInterbancaria in 'ULstTransfInterbancaria.pas' {FormLstTransferenciasInterBancarias},
  UCambioFechaTransferenciaEfe in 'UCambioFechaTransferenciaEfe.pas' {FormCambioFechaTransferencia},
  URevisionVencimientos in 'URevisionVencimientos.pas' {FormRevisionVencimientos},
  UBusca_Det_Ing_Egre in 'UBusca_Det_Ing_Egre.pas' {FormBusdadorDetIngEgr},
  UDepurarLog in 'UDepurarLog.pas' {FormDepurarLog},
  DMSaldosClientes in 'DMSaldosClientes.pas' {DatosSaldoClientes: TDataModule},
  UListadoGralCCtePersonal in 'UListadoGralCCtePersonal.pas' {FormListadoCCtaPersonal},
  ULiqGranos in 'ULiqGranos.pas' {FormLiqGranos},
  DMLiqGranos in 'DMLiqGranos.pas' {DatosLiqGranos: TDataModule},
  UCrearLstPersonalizada in 'UCrearLstPersonalizada.pas' {FormCrearLstPersonalizada},
  UCambiaNroSolo in 'UCambiaNroSolo.pas' {FormCambiaNroOPago},
  UZPrint in 'UZPrint.pas' {FormPrintVirtual},
  UListadoArticulosPresupuesto in 'UListadoArticulosPresupuesto.pas' {FormListadoArticulosPresupuesto},
  UModCotizCpbte in 'UModCotizCpbte.pas' {FormCambioCotizCpbte},
  UResumenGeneralCajas in 'UResumenGeneralCajas.pas' {FormResumenGralCajas},
  UBuscadorPresupuestos in 'UBuscadorPresupuestos.pas' {FormBuscadorPresupuestos},
  ULstChequesBCRA in 'ULstChequesBCRA.pas' {FormLstCheRechazados},
  UProxyBCRA in 'UProxyBCRA.pas',
  UClientModuleBCRA in 'UClientModuleBCRA.pas' {CModuleBCRA: TDataModule},
  UPromoCanArt in 'UPromoCanArt.pas' {FormPromo_x_Cant},
  UReproweb in 'UReproweb.pas' {FormReproWeb},
  UAdminFcCredito in 'UAdminFcCredito.pas' {FormAdministracionFcCredito},
  USeparadorTXT in 'USeparadorTXT.pas' {FormSepardorTXT},
  ListadoHist_Precio in 'ListadoHist_Precio.pas' {FormListadoHistorialPrecio},
  DMPtoVtaMorphi in 'DMPtoVtaMorphi.pas' {DatosImportaPtoVtaMorphi: TDataModule},
  SystelConn in 'SystelConn.pas',
  UAdministradorPLU in 'UAdministradorPLU.pas' {FormAdministradorPLU},
  UUsuariosRubStock in 'UUsuariosRubStock.pas' {FormUsuarioRubroLista},
  ULstOProduccionDetalle in 'ULstOProduccionDetalle.pas' {FormListadoPedidosPI},
  UListadoComprasCabDet in 'UListadoComprasCabDet.pas' {FormListadoComprasCabDet},
  UArqueoCaja in 'UArqueoCaja.pas' {FormArqueoCaja},
  UIngresoValores in 'UIngresoValores.pas' {FormValores},
  UEleccionCliente in 'UEleccionCliente.pas' {FormEleccionClientes},
  URubrosOrdenador in 'URubrosOrdenador.pas' {FormRubroOrdenador},
  UStockTipoAdicional in 'UStockTipoAdicional.pas' {FormStockTipoAdicional},
  URecpcionRepartoExpress in 'URecpcionRepartoExpress.pas' {FormRecepRepartoExpress},
  UPresupuetoIncidencias in 'UPresupuetoIncidencias.pas' {FormPresupuestoIncidencias},
  UListaCheRemplazados in 'UListaCheRemplazados.pas' {FormListadoCheRemp},
  UPlantillaRecReparto in 'UPlantillaRecReparto.pas' {FormPlantillaRecepReparto},
  USeccionCategoria in 'USeccionCategoria.pas' {FormSeccionCategorias},
  UStockTree in 'UStockTree.pas' {FormArmadoAdicionalPlantillaPedidos},
  UEsquemaLista in 'UEsquemaLista.pas' {FormEsquemaPrecios},
  UABCProveedores in 'UABCProveedores.pas' {FormABCProveedores},
  UCargarLoteTC in 'UCargarLoteTC.pas' {FormCargaLoteTC},
  UListadoPedidosPrevision in 'UListadoPedidosPrevision.pas' {FormListadoPedidosPrevision},
  DMListaPrecioEspecial in 'DMListaPrecioEspecial.pas' {DatosListaPrecioEspecial: TDataModule},
  UCargaDetalleOC in 'UCargaDetalleOC.pas' {FormControlDetalleOC},
  UReasigancionPedidos in 'UReasigancionPedidos.pas' {FormReAsignacionPedidos},
  UAltaEventoTareas in 'UAltaEventoTareas.pas' {FormAltaEventoTareas},
  URestaurarPapelera in 'URestaurarPapelera.pas' {FormRestaurarPapelera},
  UCargaSectorObras in 'UCargaSectorObras.pas' {FormCargaSectorObra},
  DMListaPreciosProv in 'DMListaPreciosProv.pas' {DatosListaPrecioProv: TDataModule},
  UBorradorInventario in 'UBorradorInventario.pas' {FormBorradorInventario},
  UStockAlquiler in 'UStockAlquiler.pas' {FormStockAlquiler},
  UCtrFechasEventosTareas in 'UCtrFechasEventosTareas.pas' {FormGestionFechasEventos},
  DMOrdenProduccion in 'DMOrdenProduccion.pas' {DatosOProduccion: TDataModule},
  UAltaObraSocial in 'UAltaObraSocial.pas' {FormObraSocial},
  UImportarMercadoPago in 'UImportarMercadoPago.pas' {FormImportarMercadoPago},
  UPacientes in 'UPacientes.pas' {FormPacientes},
  UBuscadorCpbte_Despachante in 'UBuscadorCpbte_Despachante.pas' {FormBuscaCpbteDesp},
  UListadoVentasCabDet in 'UListadoVentasCabDet.pas' {FormListadoVentasCabDet},
  UBuscadorCodRipsa in 'UBuscadorCodRipsa.pas' {FormBuscadorCodRipsa},
  UPaises in 'UPaises.pas' {FormPaises},
  UNotaCreditoAplicaAFactura in 'UNotaCreditoAplicaAFactura.pas' {FormNotaCreditoAplicaAFactura},
  UListadoArtiProduccion in 'UListadoArtiProduccion.pas' {FormListadoArticulosProduccion},
  DMImportarStock in 'DMImportarStock.pas' {DatosImportarStock: TDataModule},
  DMImportacionStock_Remoto in 'DMImportacionStock_Remoto.pas' {DatosImportarStockRemoto: TDataModule},
  DMComprobantes in 'DMComprobantes.pas' {DatosComprobantes: TDataModule},
  UAltaConsulta_CAEA in 'UAltaConsulta_CAEA.pas' {FormAltaConsulta_CAEA},
  UGraficaVentas in 'UGraficaVentas.pas' {FormABMBase4},
  DMAcopio in 'DMAcopio.pas' {DatosAcopio: TDataModule},
  DMPedidos in 'DMPedidos.pas' {DatosPedidos: TDataModule},
  ULectorLibroIvaDigital in 'ULectorLibroIvaDigital.pas' {FormLectorLibroIvaDigital},
  UCierreCajaGeneral in 'UCierreCajaGeneral.pas' {FormCierreCajaGeneral},
  UBuscadorCuentaGastos in 'UBuscadorCuentaGastos.pas' {FormBuscadorCuentaGastos},
  DMCierreCajaGeneral in 'DMCierreCajaGeneral.pas' {DatosCierreCajaGeneral: TDataModule},
  UControlUsuarios_2 in 'UControlUsuarios_2.pas' {FormControlUsuarios_2},
  UDetallesEntregas in 'UDetallesEntregas.pas' {FormDetalleEntregas},
  UListadoNovedadesEntregas in 'UListadoNovedadesEntregas.pas' {FormEntregasPedidos},
  UTipoObra in 'UTipoObra.pas' {FormTipoObra},
  UMontoAnticipo in 'UMontoAnticipo.pas' {FormMontoAnticipo},
  UPersonalCategorias in 'UPersonalCategorias.pas' {FormPersonalCategorias},
  UPersonalABMConceptos in 'UPersonalABMConceptos.pas' {FormABMPersonalConceptos},
  UPersonal_Liquidacion in 'UPersonal_Liquidacion.pas' {FormPersonalliquidacion},
  DMLiquidacionSueldos in 'DMLiquidacionSueldos.pas' {DatosLiquidacionSueldo: TDataModule},
  UStock_CargaExpress in 'UStock_CargaExpress.pas' {FormStock_Express},
  UBuscadorSubRubrosStock_2 in 'UBuscadorSubRubrosStock_2.pas' {FormBuscadorSubRubro_RubroStock},
  UDepositosVendedor in 'UDepositosVendedor.pas' {FormDepositoVendedor},
  UEgresos in 'UEgresos.pas' {FormEgresos},
  UControlCheCompartidos in 'UControlCheCompartidos.pas' {FormControlCheCompartidos},
  DMLstRefContable in 'DMLstRefContable.pas' {DatosLstRefContable: TDataModule},
  UImportacionFacCompraAFIP in 'UImportacionFacCompraAFIP.pas' {FormImportarFcCompraAFIP},
  UCambiarBcoTX in 'UCambiarBcoTX.pas' {FormCambiaBcoTx},
  UCopola in 'UCopola.pas' {FormLeerCopola},
  UTipoLiquidacion in 'UTipoLiquidacion.pas' {FormTipoLiquidacionSueldos},
  UMatafuegos in 'UMatafuegos.pas' {FormMatafuego},
  UInformeSemanal in 'UInformeSemanal.pas' {FormInformeSemanal},
  UImportacionFacVentaAFIP in 'UImportacionFacVentaAFIP.pas' {FormImportarFcVentaAFIP},
  ULecturaRelojPersonal in 'ULecturaRelojPersonal.pas' {FormLectorRelojPersonal},
  UControlNetosOPago in 'UControlNetosOPago.pas' {FormControlNetosOPago},
  UAgregarMovCaja_Efectivo in 'UAgregarMovCaja_Efectivo.pas' {FormAgregarMovCaja_Efectivo},
  UNextBin in 'UNextBin.pas' {FormNextByn},
  UCambioListaPrecios in 'UCambioListaPrecios.pas' {FormCambioListaPrecios},
  UOProduccionIncidencias in 'UOProduccionIncidencias.pas' {FormOProduccionIncidencias},
  UHoras_2 in 'UHoras_2.pas' {FormIngresoHoras},
  UAnulacionOProduccion in 'UAnulacionOProduccion.pas' {FormAnulacionOProduccion},
  UMapaHojaCarga in 'UMapaHojaCarga.pas' {FormMapaHojaCarga},
  UPlanillaSalucla in 'UPlanillaSalucla.pas' {FormPlanillaCarnes},
  UImportarHASAR in 'UImportarHASAR.pas' {FormImportarHasar},
  UEtiquetas_Compra in 'UEtiquetas_Compra.pas' {FormEtiquetasCompra},
  UBorradorOCompra in 'UBorradorOCompra.pas' {FormBorradorOC},
  UListadoCliente_LDR in 'UListadoCliente_LDR.pas' {FormListadoClientes_LDR},
  UBorradorInventarioConsulta in 'UBorradorInventarioConsulta.pas' {FormBorradorInventarioConsulta},
  UListadoBorradoOC in 'UListadoBorradoOC.pas' {FormListadoBorradoOC},
  UPedidoCOT in 'UPedidoCOT.pas' {FormPedidoCOT},
  UImportarLoteCheques in 'UImportarLoteCheques.pas' {FormImportarLoteChePropios},
  DMConversorVta_Comp in 'DMConversorVta_Comp.pas' {DatosConversorVta_Comp: TDataModule},
  UPruebaGoogle in 'UPruebaGoogle.pas' {FormTestGoogleMap},
  UListasActualizables in 'UListasActualizables.pas' {FormListasActualizanPrecio},
  DMWordPress in 'DMWordPress.pas' {DatosWordPress: TDataModule},
  WooCommerceAPI in 'WooCommerceAPI.pas',
  ULstPercepcionesIvaVta in 'ULstPercepcionesIvaVta.pas' {FormLstPercepcionesIvaVta},
  UDashBoardCliente in 'UDashBoardCliente.pas' {FormDashBoardCliente},
  UCopiasBK_Thread_JV in 'UCopiasBK_Thread_JV.pas',
  UAltaProductosCliente in 'UAltaProductosCliente.pas' {FormAltaProdutosCliente},
  UHistorialPreciosProduccion in 'UHistorialPreciosProduccion.pas' {FormHistorialPreciosProduccion},
  UPersonalNovedades in 'UPersonalNovedades.pas' {FormPersonalNovedades},
  UPrevisionCompraProveedor in 'UPrevisionCompraProveedor.pas' {FormPrevisionCompraProveedor},
  UImportarRubGastos in 'UImportarRubGastos.pas' {FormImportarRubGastos},
  UVentaCentroCosto in 'UVentaCentroCosto.pas' {FormVentasPorCentroCosto},
  URecibosTemporales in 'URecibosTemporales.pas' {FormReciboTemporal},
  UArchivosAxum in 'UArchivosAxum.pas' {FormAxum},
  UListadoArticulosUsoProduccion in 'UListadoArticulosUsoProduccion.pas' {FormAticulosUsadosProduccion},
  UListadoValoresOrdenPago in 'UListadoValoresOrdenPago.pas' {FormListadoValoresOPago},
  UImportarStockProveedorXLS in 'UImportarStockProveedorXLS.pas' {FormImportaProveeStockXLS},
  UCambioPrecioExpress in 'UCambioPrecioExpress.pas' {FormCambioPrecioExpres},
  UIncrementoMargen in 'UIncrementoMargen.pas' {FormIncrementoMargen},
  ULectorPedidosApp in 'ULectorPedidosApp.pas' {FormLectorPedidosApp},
  UUsuariosRubrosMovil in 'UUsuariosRubrosMovil.pas' {FormRubrosListaMovil},
  UUsuariosMovil in 'UUsuariosMovil.pas' {FormUsuariosMoviles},
  UCompCarnesMedias in 'UCompCarnesMedias.pas' {FormMediasResesCompra},
  UAsignaObra in 'UAsignaObra.pas' {FormAsignaObras},
  UListadoGastosObra in 'UListadoGastosObra.pas' {FormListadoGastosObra},
  UListadoRecepciones in 'UListadoRecepciones.pas' {FormListadoRecepciones},
  UControlChe3_Opago in 'UControlChe3_Opago.pas' {FormControlChe3_OP},
  UProductosVariables in 'UProductosVariables.pas',
  UCambioProveedorListaPrecios in 'UCambioProveedorListaPrecios.pas' {FormCambioProveedorLista},
  UInformarCAEA in 'UInformarCAEA.pas' {FormInformarCAEA},
  UDMain_FD in 'UDMain_FD.pas' {DMMain_FD: TDataModule},
  ULotesStock in 'ULotesStock.pas' {FormLotesStock},
  ULoteProduccion in 'ULoteProduccion.pas' {FormLoteProduccion},
  UGeneradorPartesDiarios in 'UGeneradorPartesDiarios.pas' {FormGeneradorParteDiarios},
  USectoresPedido in 'USectoresPedido.pas' {FormSectorPedidos},
  UStock_Variaciones in 'UStock_Variaciones.pas' {FormStockVariaciones},
  URemitarPedidosAgrupados in 'URemitarPedidosAgrupados.pas' {FormPedidosAProcesar},
  UPresupuestosACobrar in 'UPresupuestosACobrar.pas' {FormPrespuestoAlCobro},
  UListaLotes in 'UListaLotes.pas' {FormListaLotes},
  UDetalleFacturaPresupuesto in 'UDetalleFacturaPresupuesto.pas' {FormDetallePresuFac},
  UBorradorRegistrPikeo in 'UBorradorRegistrPikeo.pas' {FormBorradoRegistroPikeo},
  UListadoMateriasPrimasUsadas in 'UListadoMateriasPrimasUsadas.pas' {FormListadoMateriasPrimasUsadas},
  UBalanzaSerie in 'UBalanzaSerie.pas' {FormLecturaBascula},
  UKanbanPresupuesto in 'UKanbanPresupuesto.pas' {FormKanbanPrespuesto},
  UControlDepositosStock in 'UControlDepositosStock.pas' {FormDepositosControlados},
  UEmisionRotulos_2 in 'UEmisionRotulos_2.pas' {FormRotulos_2},
  UCargaCheRc in 'UCargaCheRc.pas' {FormCargaChe3},
  UListadoTarjetasCSV in 'UListadoTarjetasCSV.pas' {FormLoteLiquidacion},
  UMuestraCuponTarjeta in 'UMuestraCuponTarjeta.pas' {FormMuestraCuponTarjeta},
  FE_Utils2 in 'C:\Program Files (x86)\Embarcadero\Studio\23.0\Librerias\Feafip JC\FE_Utils2.pas' {dmFE1: TDataModule},
  Arca_personaServiceA51 in 'C:\Program Files (x86)\Embarcadero\Studio\23.0\Librerias\Feafip JC\Arca_personaServiceA51.pas',
  UOdenTarjetasC in 'UOdenTarjetasC.pas' {FormOrdenTC},
  UConultasIA in 'UConultasIA.pas' {FormConsultaIA},
  UFirebirdSQLFromIA in 'UFirebirdSQLFromIA.pas',
  ULectorPDF in 'ULectorPDF.pas' {FormLeerPDF},
  UOpenAILeerPDF in 'UOpenAILeerPDF.pas',
  UArca_Fex in 'C:\Program Files (x86)\Embarcadero\Studio\23.0\Librerias\Feafip JC\UArca_Fex.pas' {dmFEX: TDataModule},
  UArticulosEceptuadosIVA in 'UArticulosEceptuadosIVA.pas' {FormArtciculosEceptuadosIVAVta},
  UPrecioImportFNC_VCL in 'UPrecioImportFNC_VCL.pas',
  UNovedadesDetVtas in 'UNovedadesDetVtas.pas' {FormNovedadesDetVentas},
  UUsuariosAdminNP_Movil in 'UUsuariosAdminNP_Movil.pas' {FormAdministrador_NP_Movil},
  UEleccionTransporte in 'UEleccionTransporte.pas' {FormEleccionTransporte},
  URegistroDiarioOP in 'URegistroDiarioOP.pas' {FormRegistroDiarioOP},
  UBuscadoDetalleOP in 'UBuscadoDetalleOP.pas' {FormBuscadoDetalleOP},
  UControlTransacciones in 'UControlTransacciones.pas' {FormControlTransacciones},
  UAsignarSectorProduccion in 'UAsignarSectorProduccion.pas' {FormAsignarSectorProduccion},
  UReasignacionPartesDiarios in 'UReasignacionPartesDiarios.pas' {FormReasignacionPartesDiarios},
  UHojaDeCarga in 'UHojaDeCarga.pas' {FormHojaDeCarga},
  URferenciasTCPlataformas in 'URferenciasTCPlataformas.pas' {FormRef_TCPlataformas},
  UNovedadesFact in 'UNovedadesFact.pas' {FormListadoNovedadesFac},
  ULeerOrdenWP in 'ULeerOrdenWP.pas' {FormLeerOrdenWP},
  ActualizaCostoUltCompra in 'ActualizaCostoUltCompra.pas' {FormActualizaCostoUltCompra};

{$R *.RES}

begin
  FormPresentacion  := TFormPresentacion.Create(Application);
  FormPresentacion.Show;
  FormPresentacion.BringToFront;
  FormPresentacion.Update;
  // i:=0;
  // repeat
  // i:=i+1;
  // until i=5000;

  // FormDistribuidores.Show;
  // FormDistribuidores.Update;
  Sleep(3000);
  FormPresentacion.Hide;
  FormPresentacion.Free;
  //ReportMemoryLeaksOnShutdown:=True;
  Application.Title := 'Gestion de Ventas';
  Application.CreateForm(TDMMain_FD, DMMain_FD);
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TdmFE1, dmFE1);
  Application.CreateForm(TdmFEx, dmFEx);
  Application.Run;
end.




























